### ISSUE TITLE
Change the enuse_timeseries.csv column names

### ISSUE THREAD

**Issue by rajeee** [NREL/OpenStudio-HPXML#1004]
Currently, the enduse_timeseries.csv column names follow a format like this:
"end use: fule type: <end use>". 
Example:
"end use: electricity: lighting interior"

Two issues with this:
1. The unit is not evident
2. The colon ":" and the space in the column name [causes problem downstream in Athena. ](https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html)

I recommend replacing all ":" and spaces with underscore, and appending the unit. For example:
end_use__electricity__lighting_interior__kwh
(Notice there are two underscore between end_use and electricity. This is deliberate to allow for finding the fuel type by splitting on double underscore and selecting the second element. )

**Comment by shorowit** [comment]
@rajeee The column names are intentionally human readable, they are consistent with the names in results_annual.csv, and they work well for many end user applications (like DView and Excel). Is it not easy to reformat the column names when the data is loaded into Athena? Then you would have full control over what they look like for your use case.

If you absolutely can't handle it downstream, I'm willing to consider a new _optional_ argument in the `ReportSimulationOutput` measure that allows the format to be changed and defaults to the current behavior. But I definitely would not support simply replacing the previous format with the new format, we try to limit breaking changes for downstream users of OS-HPXML.

**Comment by rajeee** [comment]
@shorowit I can rename them in buildstockbatch, no problem. Was thinking it might make sense to rename them everywhere for consistency, but I understand your point regarding keeping them more human readable and maintaining existing compatibility.

What about the units, though? The column names in the results_out.json have units and are very helpful. I think units in the column of enduse_timeseries.csv would have been great too!

**Comment by shorowit** [comment]
@rajeee There are units in the output file. Maybe your workflow is stripping them out?

If I run `openstudio workflow/run_simulation.rb -x workflow/sample_files/base.xml --hourly fuels --hourly enduses`, I get the following timeseries output file:

[results_timeseries.csv](https://github.com/NREL/OpenStudio-HPXML/files/8287326/results_timeseries.csv)

**Comment by rajeee** [comment]
That link says file not found, but I checked one of my files by opening in Excel and you are right. The units are there. Since they are on the second row, the current BSB workflow skipped them. I will fix it and then we will have all we need.
Thanks!

**Comment by rajeee** [comment]
I think you can close this issue. Seems like something BSB can handle.

**Comment by shorowit** [comment]
My favorite kind of resolution. 😉 Feel free to reopen if it turns out it's not so simply to handle on the BSB side.
