### ISSUE TITLE
Emmissions sum in Timeseries doesn't match with annual

### ISSUE THREAD

**Issue by rajeee** [NREL/OpenStudio-HPXML#1008]
I recently did a test run with 250 buildings and "timestep" reporting frequency and about 90% buildings are failing with this kind of error:

"failed with Measure ReportSimulationOutput reported an error with [\"Timeseries outputs (44213.643921777155) do not sum to annual output (44216.42495840756) for Emissions: [\\\"NOx\\\", \\\"scenario1\\\"]"

This works fine if I use hourly reporting frequency for the timeseries. Looks like some kind of a bug in Timeseries summation.

**Comment by rajeee** [comment]
[run.log](https://github.com/NREL/OpenStudio-HPXML/files/8306496/run.log)

run.log attached for reference.

**Comment by shorowit** [comment]
Thanks @rajeee, I'll take a look. Certainly values within 0.007% of each other should be considered close enough and not cause an error!

**Comment by rajeee** [comment]
@shorowit. Thanks.

There are cases where they differ  by a bit more too. Here are few more cleaned up examples:

Timeseries: 18264.423880292314, Annual: 18255.82826462479, Diff 0.047%
Timeseries: 18264.423880292314, Annual: 18255.82826462479, Diff 0.047%
Timeseries: 19318.192752703828, Annual: 19308.619184261148, Diff 0.05%
Timeseries: 19318.192752703828, Annual: 19308.619184261148, Diff 0.05%
Timeseries: 9883.63957962248, Annual: 9885.1820415351, Diff -0.016%
Timeseries: 9883.63957962248, Annual: 9885.1820415351, Diff -0.016%
Timeseries: 19585.955095788828, Annual: 19579.988713688203, Diff 0.03%
Timeseries: 19585.955095788828, Annual: 19579.988713688203, Diff 0.03%
Timeseries: 27515.90422914888, Annual: 27491.324625585905, Diff 0.089%
Timeseries: 27515.90422914888, Annual: 27491.324625585905, Diff 0.089%
Timeseries: 20413.81238672037, Annual: 20392.187826277022, Diff 0.11%
Timeseries: 20413.81238672037, Annual: 20392.187826277022, Diff 0.11%
Timeseries: 6642.477649453508, Annual: 6642.604923940664, Diff -0.0019%
Timeseries: 6642.477649453508, Annual: 6642.604923940664, Diff -0.0019%
Timeseries: 17483.62386674219, Annual: 17466.725715563378, Diff 0.097%
Timeseries: 17483.62386674219, Annual: 17466.725715563378, Diff 0.097%
Timeseries: 10916.612723778313, Annual: 10918.046142804022, Diff -0.013%
Timeseries: 10916.612723778313, Annual: 10918.046142804022, Diff -0.013%
Timeseries: 13692.235034466068, Annual: 13693.133744011844, Diff -0.0066%
Timeseries: 13692.235034466068, Annual: 13693.133744011844, Diff -0.0066%
Timeseries: 8689.60535840217, Annual: 8671.061613178368, Diff 0.21%
Timeseries: 8689.60535840217, Annual: 8671.061613178368, Diff 0.21%
Timeseries: 14196.075025947208, Annual: 14179.94878942394, Diff 0.11%
Timeseries: 14196.075025947208, Annual: 14179.94878942394, Diff 0.11%

There are diffs up to 0.21%. This seems small enough, but not something that can just be neglected as rounding error.

**Comment by shorowit** [comment]
@rajeee Can you provide an HPXML (and corresponding schedule CSV(s), if it references any external files) that demonstrates this? I haven't been able to reproduce the issue, so there must be something important I'm missing.

**Comment by rajeee** [comment]
[bldg0000019.zip](https://github.com/NREL/OpenStudio-HPXML/files/8307329/bldg0000019.zip)
Here is zip file of the output of a run. Maybe this can help?

**Comment by shorowit** [comment]
Hmm, I still can't reproduce the issue. I think it's probably due to one of two things:
1. There is an inconsistency between the year (2012, a leap year) and the weather date (8760 hours). Can you try setting the year to a non-leap year like 2011 or remove it altogether? (Newer versions of OS-HPXML will start throwing an error if it sees this inconsistency.)
2. The issue may be fixing in a newer version of OS-HPXML. Can you try using the latest? @joseph-robertson is about to create a resstock branch that pulls in the latest.

**Comment by rajeee** [comment]
@shorowit  I tried running without the calendar year (which I think made it pick 2007). Still the same issue.
Here is an output:
[bldg0000070.zip](https://github.com/NREL/OpenStudio-HPXML/files/8307797/bldg0000070.zip)

The simulation timestep is 60, and reporting frequency is 'timestep'.
I will try with simulation timestep of 15, and  reporting frequency of 'timestep' next.

**Comment by joseph-robertson** [comment]
We _could_. You mean just as a convenience since there is overhead before getting to actual datapoint simulations?

**Comment by rajeee** [comment]
@joseph-robertson Yeah; always good to have things early before run is submitted to eagle because sometimes it takes hours even before simulation will be run (eagle scheduling issue). But I guess there is a limit to what we can/should do early and what we have to let go.

Anyway, I redid the simulation with simulation_control_timestep of 15, and this time it worked fine.
So, looks like when simulation_control_timestep is 60, and reporting_frequency is 'timestep' there is some bug.

**Comment by shorowit** [comment]
@rajeee There we go, I was able to reproduce it with your most recent zip. I'll work on a fix.

**Comment by shorowit** [comment]
@rajeee Can you see if https://github.com/NREL/resstock/pull/857 fixes your issue?
