### ISSUE TITLE
Missing column when requesting timeseries output variable

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1038]
I ran the following:
```openstudio workflow/run_simulation.rb -x workflow/sample_files/base-dhw-indirect.xml -o test --add-timeseries-output-variable "Pump Electricity Energy"```

There are two pumps in this model, and I verified that there are two sets of timeseries data in the E+ output sql, but only one of the two ends up in the results_timeseries.csv:

![image](https://user-images.githubusercontent.com/5861765/163579883-e8bfce41-8e26-4409-82a7-7a1040cbc3f4.png)

**Comment by joseph-robertson** [comment]
I'm showing this in the IDF for the second pump:
```
Pump:VariableSpeed,
  boiler hydronic pump 1,                 !- Name
  Node 19,                                !- Inlet Node Name
  Node 25,                                !- Outlet Node Name
  0.00360576923076923,                    !- Design Maximum Flow Rate {m3/s}
  20000,                                  !- Design Pump Head {Pa}
  0,                                      !- Design Power Consumption {W}
```
Resulting in all zero timeseries output (which doesn't get selected for display in results_timeseries.csv).

@shorowit Should the second pump have non-zero consumption?

**Comment by shorowit** [comment]
Oh, I see. Yes, it should have zero consumption, but I was wanting to verify in the timeseries output that it has zero consumption. Can we include all user-requested outputs even when they are zero? (We'll still exclude other outputs, like end uses, that are zero.)
