### ISSUE TITLE
Infiltration enhancements for attached housing

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1059]
Currently the HPXML AirLeakage input for a SFA/MF unit is used directly in the model as the infiltration from outside (e.g., from a guarded test).

We should consider A) adding an HPXML element to clarify what kind of leakage value is provided, and B) if an unguarded test value is provided, automatically apply the `Aext` factor that we already calculate for ERI simulations. (`Aext` is defined by ASHRAE 62.2-2019 as the ratio of exterior envelope surface area to compartmentalization boundary area. RESNET does not allow guarded test measurements.)

**Comment by shorowit** [comment]
This should allow us to remove the [SFA/MF infiltration adjustment that ResStock is currently using](https://github.com/NREL/resstock/blob/ab9db15235869cf118c32ea45fef62e98dbb8b59/measures/ResStockArguments/measure.rb#L656-L704), for example. FYI @ejhw @joseph-robertson

**Comment by shorowit** [comment]
A nice summary of different tests from the RESNET conference:

![image](https://user-images.githubusercontent.com/5861765/166584274-6a25653a-1950-42e7-8843-5c34a2316d67.png)

**Comment by ejhw** [comment]
@shorowit Cool. Is `Aext` equivalent to the current ResStock adjustment or is it different somehow?

**Comment by shorowit** [comment]
@ejhw I think so, but we would want to test a variety of different SFA/MF units.

**Comment by shorowit** [comment]
This needs to be addressed. I think that OS-HPXML is currently inconsistent in that it A) treats the provided infiltration rate as the amount of air from outside for the infiltration model, but B) applies the `Aext` adjustment on top of the provided infiltration rate for purposes of autosizing the mechanical ventilation per 62.2.

In other words, the adjustment appears to be performed twice when the mechanical ventilation flow rate is not provided (i.e., defaulted). For an attached dwelling unit, this would incorrectly result in a lower infiltration credit, and therefore a larger mechanical ventilation flow rate requirement.
