### ISSUE TITLE
Schedule file temp directory running out of memory on Eagle

### ISSUE THREAD

**Issue by nmerket** [NREL/OpenStudio-HPXML#1070]
This is in the context of running ResStock on Eagle. The schedule file created in a temporary directory [here](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedules.rb#L1157) is being written by default as `/tmp/schedule_foo.csv`. However on an Eagle node, the `/tmp` directory is a 150 MB RAM disk.

```
Filesystem                                                                 Size  Used Avail Use% Mounted on
devtmpfs                                                                    47G     0   47G   0% /dev
tmpfs                                                                       47G     0   47G   0% /dev/shm
tmpfs                                                                       47G  3.4G   44G   8% /run
tmpfs                                                                       47G  3.2G   44G   7% /
tmpfs                                                                       47G     0   47G   0% /sys/fs/cgroup
tmpfs                                                                      150M     0  150M   0% /tmp
/dev/sda1                                                                  932G   33M  932G   1% /tmp/scratch
lead-eth:/var/lib/sgi/per-host/ice-centos7.7-slurm/4/i7n35/var/log/memlog  2.0G   72M  2.0G   4% /var/log/memlog
10.148.67.8:/home                                                          182T   48T  135T  27% /home
10.148.67.8:/nopt                                                          182T   48T  135T  27% /nopt
10.148.66.1@o2ib:10.148.66.2@o2ib:/eaglefs                                  18P   14P  3.5P  80% /lustre/eaglefs
```

It looks like in ruby you can tell the [`Tempfile.new` constructor](https://ruby-doc.org/stdlib-2.5.3/libdoc/tempfile/rdoc/Tempfile.html#method-c-new) a directory in which to place the temp file. You could detect whether you're on Eagle with the `LOCAL_SCRATCH` environment variable, which contains the path where a local 1TB local drive is stored that gets erased at the end of the job (always `/tmp/scratch`).

Another option would be to just store the schedule file in the run directory. We already store the openstudio run directory under `/tmp/scratch`. I'm not clear why this schedule file is being written as a temp file, but I'm sure you have reasons. 

@shorowit @joseph-robertson @mnblonsky @jmaguire1

**Comment by shorowit** [comment]
Since this file doesn't actually get referenced by the simulation[1], it's probably confusing to make it more visible in the run directory. So I suggest we go with the `/tmp/scratch` solution for now. @joseph-robertson Are you able to address this?

[1] OpenStudio makes a copy of it in a `files` directory, which is referenced by the simulation. Why? I don't know.

**Comment by joseph-robertson** [comment]
Yes, I can make this change.

Curious, where does the `files` directory get created?
