### ISSUE TITLE
Issues with number_of_residents=0

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1079]
Currently, there are errors for the following situations when `hpxml.building_occupancy.number_of_residents=0`:
* When generating stochastic schedules
* When occupancy calculation type is operational

**Comment by lixiliu** [comment]
Per ResStock-estimation Issue 311, Vacant units currently are associated with a number of household attributes, including income, tenure, and occupants. The consensus is to remove these attributes for vacant units going forward. I have a fix [here](https://github.com/NREL/resstock-estimation/pull/312) and would like to try and get it worked in before RECS 2020 updates. Many of the tsvs from RECS 2020 will have some dependencies on income, FPL, and occupants.

The supporting piece on the ResStock side is an ability to set Occupants=0 for Vacant units, so we need to elevate this issue and revive Joe's tentative solution for it.
