### ISSUE TITLE
Additional example files using detailed CSV schedules

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1088]
1. If running a simulation w/ a non-annual run period, does the schedule still need to be for the entire year? If so, should we allow the CSV schedule values to only be defined for the simulation run period?
2. If running a sub-hourly timestep simulation, can the schedule be at a higher time scale (e.g., hourly)? What about vice versa?

Let's add example files demonstrating these capabilities if they work. And we should make sure the documentation describes these situations.

**Comment by jmaguire1** [comment]
I'm actually in the middle of doing some lab validation of CO2 HPWHs using Schedule:File objects. 

For #1, the answer is you still need to make a schedule:file for the full year. It's actually a somewhat annoying limitation when you want to validate a model against lab data, which is usually a 6-8 hour test. I ended up just repeating the same day of data over and over again, but then I unnecessarily need to make a huge file with 525600 rows. Worse, if you don't make your file that long E+ doesn't error, it crashes, which makes it hard to figure out what the problem is.

Actually not sure on #2, but I'd be happy to try it out if that's helpful

**Comment by yzhou601** [comment]
> I'm actually in the middle of doing some lab validation of CO2 HPWHs using Schedule:File objects.
> 
> For #1, the answer is you still need to make a schedule:file for the full year. It's actually a somewhat annoying limitation when you want to validate a model against lab data, which is usually a 6-8 hour test. I ended up just repeating the same day of data over and over again, but then I unnecessarily need to make a huge file with 525600 rows. Worse, if you don't make your file that long E+ doesn't error, it crashes, which makes it hard to figure out what the problem is.
> 
> Actually not sure on #2, but I'd be happy to try it out if that's helpful

It's not only annoying that copying data again and again to make the rows, but also need to be careful that the most interesting 6-8 hours didn't get messed up. Sounds like it's worth to propose some development to E+.

**Comment by jmaguire1** [comment]
> > I'm actually in the middle of doing some lab validation of CO2 HPWHs using Schedule:File objects.
> > For #1, the answer is you still need to make a schedule:file for the full year. It's actually a somewhat annoying limitation when you want to validate a model against lab data, which is usually a 6-8 hour test. I ended up just repeating the same day of data over and over again, but then I unnecessarily need to make a huge file with 525600 rows. Worse, if you don't make your file that long E+ doesn't error, it crashes, which makes it hard to figure out what the problem is.
> > Actually not sure on #2, but I'd be happy to try it out if that's helpful
> 
> It's not only annoying that copying data again and again to make the rows, but also need to be careful that the most interesting 6-8 hours didn't get messed up. Sounds like it's worth to propose some development to E+.

I'd be interested in at least getting an error instead of a crash in this scenario. There's other improvements I can think of around model validation in E+ (mostly around how you get the right initial values), but that's a longer conversation for another day I think.

**Comment by shorowit** [comment]
Indeed the [E+ documentation says that a full year of data is needed](https://bigladdersoftware.com/epx/docs/22-1/input-output-reference/group-schedules.html#schedulefile). I see some existing issues on this topic [here](https://github.com/NREL/EnergyPlus/issues/4154) and [here](https://github.com/NREL/EnergyPlus/issues/6898).
