### ISSUE TITLE
Add units to columns in timeseries output

### ISSUE THREAD

**Issue by ejhw** [NREL/OpenStudio-HPXML#1104]
It looks like units are not present in timeseries output. I'd suggest they get added to avoid confusion, particularly because the units are different for electric and fuel end uses, and are different from the annual outputs. An external user of ResStock results got confused by this because they thought the timeseries output was in mbtu too despite reading the docs.
[Building 1 Baseline Results.csv](https://github.com/NREL/OpenStudio-HPXML/files/8779786/Building.1.Baseline.Results.csv)

What do you think @shorowit @joseph-robertson ? Let me know if this belongs at buildstockbatch or resstock repos instead.

cc @ekpresent

**Comment by shorowit** [comment]
OS-HPXML does have units for timeseries outputs, so bsb or resstock must be losing them.
[results_timeseries.csv](https://github.com/NREL/OpenStudio-HPXML/files/8779850/results_timeseries.csv)

**Comment by joseph-robertson** [comment]
The units row gets skipped in here: https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L180-L190, but then `units_dict` is used later on in https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L214-L225. Implies units are appended, so I'm not sure what's going on.

**Comment by ejhw** [comment]
My mistake, I moved to https://github.com/NREL/buildstockbatch/issues/293 . Thanks!
