### ISSUE TITLE
Bad results when AFUE=0

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1105]
For example, in `base.xml` change AFUE=0.0. In `results_annual.csv` you will see "Energy Use: Total" and "Fuel Use: Natural Gas: Total" equal to "Infinity". Should we be preventing (catching) HPXML files with AFUE not greater than zero?

**Comment by joseph-robertson** [comment]
Maybe this is a consequence of allowing OpenStudio to pass "invalid" values ([recently merged feature](https://github.com/NREL/OpenStudio/pull/4505))?

**Comment by shorowit** [comment]
Note that OS-HPXML does give a warning.

Perhaps more surprising is that A) both HPXML and EnergyPlus allow a value of zero as an input and B) a simulation output of "Infinity" doesn't cause errors/problems in _any_ of the software.

**Comment by shorowit** [comment]
My initial suggestions:
1. Propose updates to the HPXML schema so that the `Efficiency` type is MinExclude=0 instead of MinInclude=0.
2. Update the ReportSimulationOutput measure to throw an error if EnergyPlus returns "Infinity". (I didn't even know this was possible.)

**Comment by shorowit** [comment]
HPXML schema proposed change: https://github.com/hpxmlwg/hpxml/pull/319
