### ISSUE TITLE
msgpack error for reporting measures

### ISSUE THREAD

**Issue by craigers290** [NREL/OpenStudio-HPXML#1157]
The reporting measures  all include the line 
`require 'msgpack'` 

This creates an error within PAT v3.4.0 and the OpenStudio App v1.4.0. The error shows up in the measure.xml file as:
`<error>cannot load such file -- msgpack</error>`

This may be related to additional xml issues where input fields are not loading in the mentioned UI's

**Comment by shorowit** [comment]
@craigers290 That doesn't make sense to me. Don't those versions of the apps include OS 3.4.0? The OS 3.4.0 CLI includes the msgpack gem as described in [the release notes](https://github.com/NREL/OpenStudio/releases/tag/v3.4.0).

You can also verify it by running, e.g., `C:\openstudio-3.4.0\bin\openstudio.exe gem_list` and you should see msgpack in the list.

**Comment by shorowit** [comment]
Sounds like this is no longer an issue. Closing. Please reopen if I misunderstood.
