### ISSUE TITLE
Reported loads when no/partial HVAC?

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1207]
What should we report for, e.g., `Load: Cooling: Delivered`, `Peak Load: Cooling: Delivered`, and `Component Load: Cooling: Foo` if there is A) no cooling system or B) a partial cooling system (like a room AC serving 33% of the cooling load)? Some users have been confused by these outputs under these situations.

Here are the current results:

![image](https://user-images.githubusercontent.com/5861765/199359916-6e057590-d76f-4cef-885b-85c44976cdfe.png)
(base-hvac-stove-oil-only.xml has no cooling)

The inconsistency between some of the outputs for the no cooling and partial cooling cases is presumably caused by the use of a backup ideal air system to model the partial HVAC case. 

Different users or use cases may have different desired results. And there may be practical limitations in terms of what we _can_ report.

**Comment by joseph-robertson** [comment]
Should it say "base-hvac-stove-oil-only.xml has no _cooling_"?

**Comment by shorowit** [comment]
Yes, thanks. Updated.

**Comment by shorowit** [comment]
@lixiliu recently got confused by this when looking at the peak cooling load for a file w/ a room AC that meets 20% of the cooling load. The reported peak cooling load includes the ideal air system meeting the other 80% of the load.
