### ISSUE TITLE
Asset vs operational, take 2

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1234]
Should we simplify how this works in OS-HPXML?

Current behavior:
- There is an explicit optional input for asset vs operational (defaults to asset)
- If operational, number of occupants is required
- If asset, number of occupants can be provided, but it only affects occupant heat gains (confusing)
- If number of occupants is provided but the HPXML does not explicitly specify operational (such that it defaults to asset), the user may not realize they are getting asset simulation results (bad)

Proposal 1:
- Remove explicit input
- If number of occupants provided, assume operational, otherwise assume asset

Proposal 2
- Make asset vs operational a required field
- Disallow number of occupants when asset is specified and require number of occupants when operational is specified

One underlying wrinkle to all of this is that the asset calculation, per ANSI/RESNET 301, assumes the number of occupants equals the number of bedrooms. But if you were to perform an operational calculation and provide the same number of occupants, you would get a different answer as our usage adjustments are based on the relationship between occupants/bedrooms from RECS. Technically this wrinkle exists today, but it might become more apparent with either of the proposed changes. Not the end of the world, but it's mildly confusing. Regardless, it's better than the status quo on balance.

**Comment by joseph-robertson** [comment]
So for both Proposal 1 and 2 we lose the ability to do an asset calculation where the user can specify the number of occupants (and thus control occupant heat gains)?

**Comment by shorowit** [comment]
Correct, intentionally losing that to reduce confusion.
