### ISSUE TITLE
Document default values in BuildResHPXML measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1252]
Requested by a user. Can we document the default values that will be used when the user does not provide an input for a given BuildResHPXML argument? Ideally automated so that it stays in sync with actual defaulting code and documentation.

**Comment by joseph-robertson** [comment]
I'm starting to think that the need for documentation/tracking around BuildResHPXML is becoming more and more critical. I get a lot of questions that might be more conveniently answered by pointing to documentation. Questions like:
* What arguments or options aren't available in BuildResHPXML, but are supported in the HPXML file? An argument example might be `fan_watts_per_cfm` for HVAC systems. An option example might be that `HVACTypeHeatPumpWaterLoopToAir` is not a valid choice for `heat_pump_type`.
* What are all the arguments available in BuildResHPXML that aren't currently exposed/used in options_lookup.tsv? An example might be: https://github.com/NREL/resstock/issues/1084.

The second item belongs in the ResStock documentation, but perhaps could share some of the "automation" code written for the first item and the request described in this issue?
