### ISSUE TITLE
Autosized HP backup capacity when using `MaxLoad` sizing

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1322]
Currently we always size the HP backup based on the heating design load, regardless of the sizing methodology. For `ACCA` and `HERS`, the backup system will operate on the coldest day so that makes sense. But `MaxLoad` is intended to size the heat pump without needing backup, so we should probably just autosize to zero.

(It shouldn't really make a difference in terms of energy results, but it's confusing to see a large backup system for a HP sized for max load.)

**Comment by shorowit** [comment]
Note: A user can always avoid this situation today by specifying that there is no backup heating for their heat pump (that has been sized to meet the max load).

**Comment by shorowit** [comment]
@jonwinkler thinks that Manual S sizes the backup for emergency heat. Meaning, the backup is sized to meet the entire design load if the heat pump fails. Since some contractors/homeowners may not follow that suggestion, or when wiring can't meet the required ampacity of the backup, he suggests we could offer different backup sizing options, like "supplemental", "emergency", etc.

**Comment by lixiliu** [comment]
Caveat, for `MaxLoad`, HP is sized to meet heating load at design temp or min compressor lockout temp, whichever is higher. Since HP can get locked out, 100% backup is still be needed when design temp < min compressor temp.
