### ISSUE TITLE
Merge VacancyPeriods and PowerOutagePeriods into UnavailablePeriods?

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1328]
Would simplify code, reduce maintenance, and potentially support future expansion for other types of periods.

Rename https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/data/schedules_affected.csv to unavailable_periods.csv. Change column names to just "Vacancy" and "Power Outage". Add a HPXML element that calls out the column name of interest for a given UnavailablePeriod.

(Which is a better name -- UnavailablePeriod or UnavailabilityPeriod? Or something else?)

**Comment by joseph-robertson** [comment]
If we go with UnavailablePeriods (or UnavailabilityPeriods), we should change the `off_period` method names, too.

**Comment by joseph-robertson** [comment]
Note: address `water_heater_setpoint` not being referenced by schedules_affected.csv.

**Comment by shorowit** [comment]
> If we go with UnavailablePeriods (or UnavailabilityPeriods), we should change the `off_period` method names, too.

Agreed.
