### ISSUE TITLE
Ambient foundation height from ground not available

### ISSUE THREAD

**Issue by nmerket** [NREL/OpenStudio-HPXML#1355]
Up until #1340 we were assuming that ambient foundations were sitting on the ground so no wind was experienced by that floor. See https://github.com/NREL/OpenStudio-HPXML/pull/1340/commits/8e664d685b9f91c99e86125eaee79f1270876671. Now we have to make an assumption about how high off the ground an ambient foundation is (2ft by the way). It would be good to have this as an input somewhere. This will probably require new HPXML elements.

**Comment by shorowit** [comment]
This could also apply to the height of an apartment unit that is, e.g., above another unit. Is it 10 ft off the ground or 50?

**Comment by shorowit** [comment]
Create a new `StoryOfUnit` (or somilar) element for HPXML?
