### ISSUE TITLE
Allow modeling whole SFA/MF buildings

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1376]
Currently OS-HPXML only allows modeling individual dwelling units of a SFA/MF building (including workarounds for MF common spaces adjacent to the unit or units with shared HVAC/DHW/ventilation systems, per ANSI 301).

However, there are use cases where it would be highly beneficial to create whole MF building models. The easiest path from here to there would be to allow a HPXML file where each dwelling unit is described as an individual `Building` element. The HPXMLtoOpenStudio measure could be updated to create an individual model for each `Building` element (as it does now) and then merge all the models into a single whole-building model (see [example code from URBANopt](https://github.com/urbanopt/urbanopt-example-geojson-project/blob/develop/example_project/measures/BuildResidentialModel/measure.rb#L160-L336)) at the end. Ideally, the BuildResidentialHPXML measure would also be updated to produce HPXML files like this.

(There could be another use case where someone wants to provide an HPXML in which a single `Building` element describes the entire MF building -- e.g., 30 units, 3 stories, 60 bedrooms, 20000 sqft, etc. -- but that would be a greater departure from how OS-HPXML works and far more effort.)

Some things to consider for this approach:
- Common spaces and surface adjacency
- Shared/central systems
- Unit multipliers
- Coordination w/ openstudio-standards and other existing products
- Output reporting

**Comment by joseph-robertson** [comment]
I think your "30 units, 3 stories, 60 bedrooms, 20000 sqft, etc." example is somewhat close to how URBANopt operates. Entire MF building "features" are described at the whole-building level, along with "number of dwelling units represented". The measure supporting the merge of all models starts by scaling all building-level properties down according to the number of dwelling units represented value.

**Comment by shorowit** [comment]
But URBANopt never ends up with an HPXML file that describes the entire MF building like that -- it fundamentally generates a single HPXML `Building` element for each dwelling unit.

I'm trying to make the point that it's a not-too-big step to support the type of HPXML files that URBANopt produces, but if URBANopt were to provide a HPXML file that fundamentally reflected its higher-level inputs, that would be a much bigger effort.

**Comment by joseph-robertson** [comment]
Yeah I just meant in terms of collecting inputs at the whole-building level, not in terms of storing them in HPXML.

**Comment by joseph-robertson** [comment]
I've been thinking a bit about this issue. Perhaps one way we could update the BuildResidentialHPXML measure to produce HPXML files with multiple `Building` elements, would be to introduce a new optional `hpxml_path_in` argument (or change current `hpxml_path` argument to `hpxml_output_path`, and then add new `hpxml_path`). When provided, the measure _appends_ a new `Building` element; when not provided the HPXML output file has exactly one `Building` element. Users of the measure could then apply BuildResidentialHPXML in series to describe a SFA/MF building.

**Comment by shorowit** [comment]
Ideally we would update the reporting measures to produce results for each unit (and the building total).

**Comment by shorowit** [comment]
Work plan:
- @shorowit + @joseph-robertson: Update HPXMLtoOpenStudio measure to support creation of single OSM
- ??: Update ReportSimOutput measure as needed
- @joseph-robertson: Update BuildResHPXML measure to support creation of single HPXML w/ multiple `Building` elements
- @shorowit + @joseph-robertson: Somehow allow unit multipliers (e.g., E+ zone multipliers w/ additional logic for any gaps, changes to reporting measure, etc.)
- ??: Update ReportUtilityBills as needed (Don't support whole MF buildings? Use average unit consumption for bill calcs? Or do we need consumption for each unit? What about central meters?)
- @shorowit: Allow modeling of common spaces as E+ thermal zones

**Comment by shorowit** [comment]
- Give a warning if unit multipliers w/ stochastic schedules?

**Comment by shorowit** [comment]
- Combine unconditioned zones into a single zone for each type (e.g., attic, unconditioned basement, etc.)?
