### ISSUE TITLE
Update to 2022 EIA energy costs

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1382]
EIA 2022 data is out. Electricity rates are ~10% higher and natural gas rates are ~20% higher than 2021.

@joseph-robertson, is this something you can do?

**Comment by joseph-robertson** [comment]
Update the files in ReportUtilityBills's [simple_rates](https://github.com/NREL/OpenStudio-HPXML/tree/master/ReportUtilityBills/resources/simple_rates) resources folder? Yes, I think so.

**Comment by shorowit** [comment]
Can we also refactor the tests to make it easier to update?
