### ISSUE TITLE
[question] download_utility_rates downloads CSV/gzip and converts to JSON. Is it the same as the OpenEI JSON format?

### ISSUE THREAD

**Issue by jmarrec** [NREL/OpenStudio-HPXML#1411]
the task `download_utility_rates` downloads the USURB rates in the CSV/gzip and appear to be processing it to the OpenEI JSON format.

There is a json/gzip available for the USURB https://openei.org/wiki/Utility_Rate_Database so I wonder why you aren't using it directly? 
     * Is this only for legacy reasons, as in the JSON/gzip didn't exist before? 
     * Or somehow the JSON/gzip uses an older version than version=7?

**More importantly, if I were to download a rate from the OpenEI  API in JSON format directly, would it work? Or that the two not actually equivalent?**

---

https://github.com/NREL/resstock/blob/ec155ed4a0748bbbbe26b8abfee7d4c23507bc81/resources/hpxml-measures/tasks.rb#L2187-L2215

Processing seems to imply this is equivalent:

https://github.com/NREL/resstock/blob/ec155ed4a0748bbbbe26b8abfee7d4c23507bc81/resources/hpxml-measures/ReportUtilityBills/resources/util.rb#L453-L455

**Comment by shorowit** [comment]
The JSON/gzip is not a gzip of OpenEI JSON files, but rather a single enormous JSON file that is a raw dump of the database. So it's identical to the CSV file that we're using, but in JSON format. It was easier to just work with the CSV file between the two. The only way to get OpenEI JSON files is to do API calls, which we were leery of.

It's the intention that the JSON files we produce should be equivalent to those downloaded from the API.

Anyway, that's my recollection, but @joseph-robertson did the actual work so he may remember more/better.

**Comment by joseph-robertson** [comment]
This sounds accurate.

To further the "It [the CSV/gzip file] was easier to work with" point, we had at one time pursued the JSON/gzip. But upon opening it and inspection, noticed it contained some weird formatting due to mongoexport (?). Not sure if that's still the case, but at the time it was better to just go with the CSV/gzip.

**Comment by shorowit** [comment]
Feel free to reopen if that doesn’t satisfy your questions.
