### ISSUE TITLE
Error if using schedules w/ mixed timesteps

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1419]
Found by @jmaguire1 using BEopt ([BEopt issue](https://github.com/NREL/BEopt/issues/215)).

If you, say, run a 10-minute simulation where one schedule has 10-minute values and another schedule has hourly values, you receive a ruby error. It'd be nice to support this rather than working around the issue in BEopt.

The error is:
```
Error: element size differs (52560 should be 8760)
/mnt/c/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/schedules.rb:1475:in `transpose'
/mnt/c/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/schedules.rb:1475:in `block in export'
:/ruby/2.7.0/csv.rb:658:in `open'
/mnt/c/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/schedules.rb:1473:in `export'
/mnt/c/git/openstudio-hpxml/HPXMLtoOpenStudio/resources/schedules.rb:1396:in `initialize'
```

It seems like the solution is to "expand" the schedules with fewer elements such that all the schedules have the same number of elements when exporting to CSV.

**Comment by shorowit** [comment]
@joseph-robertson I created a PR w/ a new sample HPXML file that hits the error. Could you help fix it? See https://github.com/NREL/OpenStudio-HPXML/pull/1420

**Comment by shorowit** [comment]
@joseph-robertson You might want to make my new test file even more complicated. Seems like the code for vacancies/power outages [assumes all schedules have the same number of elements](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedules.rb#L1616).

**Comment by shorowit** [comment]
(If fixing this proves to be too complicated, I'm open to the idea of punting and just requiring all schedules to have the same number of elements. But then we should add a user-friendly error message.)

**Comment by jmaguire1** [comment]
@shorowit: If we punt, would a user need a way to enter a schedule value every timestep rather than just hourly in BEopt? Or would this mean you can only enter schedules if you're using an hourly timestep?

**Comment by joseph-robertson** [comment]
@shorowit Could we update/refactor the `SchedulesFile` class to export more than one `in.schedulesXXX.csv` file (depending on the lengths of schedule columns)?

**Comment by joseph-robertson** [comment]
> @joseph-robertson You might want to make my new test file even more complicated. Seems like the code for vacancies/power outages [assumes all schedules have the same number of elements](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedules.rb#L1616).

I placed a new `expand_schedules` method _ahead_ of this line.

**Comment by shorowit** [comment]
@joseph-robertson Good idea. That's smart.
