### ISSUE TITLE
BuildResHPXML measure: Update ducts CFA served when load fraction served < 1

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1440]
Currently the air distribution system's CFA served defaults to the entire home's CFA:
https://github.com/NREL/OpenStudio-HPXML/blob/4f093def65dd438569b5829529dd75ffe7a48db9/BuildResidentialHPXML/measure.rb#L5111-L5114

That's usually right. But if the ducted HVAC system only serves a fraction of the load (e.g., because there is a secondary system), then the CFA served should be similarly reduced. Perhaps the CFA served should equal `CFA x max(fraction_heat_load_served, fraction_cool_load_served)`?

**Comment by lixiliu** [comment]
Is this the right list of load_served to consider?
```
 args[:geometry_unit_cfa] * [
        args[:heating_system_fraction_heat_load_served], 
        args[:cooling_system_fraction_cool_load_served],
        args[:cooling_system_integrated_heating_system_fraction_heat_load_served],
        args[:cooling_system_integrated_heating_system_fraction_cool_load_served],
        args[:heat_pump_fraction_heat_load_served],
        args[:heat_pump_fraction_cool_load_served],
      ].max # TODO: do we need to consider mech_vent_shared_preheating_fraction_heat_load_served and cool_load_served?
```

**Comment by shorowit** [comment]
It needs to be more focused than that. It should only apply to ducted HVAC systems that are attached to the air distribution system. (For example, `args[:cooling_system_fraction_cool_load_served]` might apply to a room air conditioner.)

I worked up a proposal right when I created the issue, I'll push what I have to a PR. But it still needs testing.

**Comment by lixiliu** [comment]
I am asking because we need an equivalent way to get the same thing on the resstock side since we need cfa_served to do duct surface area calc.
