### ISSUE TITLE
Separate ground conductivities for foundations vs. gshps

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1479]
See https://github.com/NREL/OpenStudio-HPXML/pull/1391 for context.

From Matt:
"From a modeling perspective, I'd say yes, but from a practical perspective, I'd say no. The vertical conductivity from a thermal response test (which is what is the typical best practice) is an "effective" measurement of all of the various layers of soil, moisture, water, voids, etc. The foundation value should be much more representative of the surface materials, which is going to be affected by the rain, evapotranspiration from the soil, etc."

**Comment by shorowit** [comment]
@afontani What's your thinking here? Can we stick with a single input or do you think it's important to have separate inputs?

**Comment by shorowit** [comment]
This feels like an advanced feature that an OS-HPXML user would _rarely_ want/use. I'm going to close this. If someone really needs to do this, they can add another OS measure into the workflow to make the change.
