### ISSUE TITLE
AC/HP sizing bug in cooling adjustment

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1508]
This equation has a unit conversion issue:

https://github.com/NREL/OpenStudio-HPXML/blob/2e750ede8de83b1e489df36a883c71acb984e736/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L1383-L1386

This can result in a negative value being calculated. Code further down will check for a negative value and set the cooling capacity based on the ACCA Manual S oversize limit, so the bug was easily missed.

We should also double-check this equation:

https://github.com/NREL/OpenStudio-HPXML/blob/2e750ede8de83b1e489df36a883c71acb984e736/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L1423-L1426

**Comment by jonwinkler** [comment]
I confirmed the unit conversions in the following lines are indeed correct. 

[https://github.com/NREL/OpenStudio-HPXML/blob/2e750ede8de83b1e489df36a883c71acb984e736/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L1424C1-L1425](url)
