### ISSUE TITLE
Sizing control option to specify max allowed airflow 

### ISSUE THREAD

**Issue by jonwinkler** [NREL/OpenStudio-HPXML#1556]
@joseph-robertson @yzhou601 @shorowit 

It would be useful to implement an argument for passing in the calculated maximum airflow rate for existing ducts  (`hvac_distribution_duct_max_airflow_cfm`). Analogous to system capacities, ResStock could use ApplyUpgrade to assign the values corresponding to the existing building. This could make sizing heat pump upgrades (i.e., a new advanced [HVAC sizing control input](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-hvac-sizing-control)) more realistic where the maximum allowed airflow rate could be based on the baseline.

**Comment by joseph-robertson** [comment]
https://github.com/NREL/OpenStudio-HPXML/pull/1547 aims to address this. https://github.com/NREL/resstock/pull/1163 tries it out in ResStock.
