### ISSUE TITLE
Allow for an optional furnace oversizing factor

### ISSUE THREAD

**Issue by jonwinkler** [NREL/OpenStudio-HPXML#1561]
Furnaces tend to be oversized. ACCA allows a furnace oversizing factor of 1.4 and AFUE calculations assume furnaces are oversized by 1.7. Allowing a specified furnace oversizing factor could impact heat pump sizing in cold climates when limited the heat pump size to the maximum heating or cooling airflow rate in the baseline building.

This could be an optional sizing input in the [HPXML HVAC Sizing Control](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-hvac-sizing-control) node.

**Comment by yzhou601** [comment]
@shorowit @jonwinkler I think I read the issue that the scope of this feature is just for furnace, but was not very clear when reading the discussions in https://github.com/NREL/resstock/issues/1091.
