### ISSUE TITLE
Allow GSHP w/ separate backup

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1565]
In ResStock, I tried a GSHP w/ separate backup. It caused the following error:
```
[10:55:03.754973 ERROR] undefined method 'supp_max_temp' for #<HPXML::AdditionalProperties design_chw=85.0, design_delta_t=10.0, ...
```

It appears that `hpxml_defaults.rb` doesn't call `HVAC.set_heat_pump_temperatures` for GSHP: https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hpxml_defaults.rb#L1483-L1504

This is the line that causes the error: https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hvac.rb#L2902

**Comment by jmaguire1** [comment]
@joseph-robertson: Can I ask why you ran this scenario? One of the big advantages of a GSHP is that the ground temperature is much more stable than the outdoor air temperature, so you shouldn't need to have backup heat if you have a GSHP.

Basically, do we think this case is supposed to work? Do we want to support a backup system for GSHPs, or should we have not allowed this combination/error out?

**Comment by joseph-robertson** [comment]
I was just adding an example GSHP upgrade to our sample files in ResStock. It was not meant to necessarily reflect real world practice.

Sounds like we don't want to allow GSHP with backup. We therefore should _gracefully_ throw a warning or error, and avoid hitting the error above.

**Comment by afontani** [comment]
@joseph-robertson , @jmaguire1 : Integrated backup is rare with GSHPs. There are possibly secondary, but not integrated backup systems with GSHPs. I also talked to the lead engineer at Dandelion and they said they rarely use integrated backup systems with their GSHPs, but will if the client asks for it directly.

**Comment by shorowit** [comment]
We shouldn't prevent it just because its uncommon, but it's certainly not a high priority.
