### ISSUE TITLE
Use ModelMerger?

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1591]
See https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.7.0-doc/model/html/classopenstudio_1_1model_1_1_model_merger.html

Maybe it can replace some of our code related to merging individual dwelling units for whole MF building models.

**Comment by joseph-robertson** [comment]
ModelMerger rings a bell in the context of URBANopt. I feel like I may have at least looked into this during the design of the URBANopt version of this implementation. But I'd need to do some digging.

**Comment by shorowit** [comment]
Probably not worth pursuing at this point, we have something that is working.
