### ISSUE TITLE
Double check HP backup autosizing wrt/ min compressor temp

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1595]
If HP min compressor temp > design temp, we [size the HP to the min compressor temp](https://github.com/NREL/OpenStudio-HPXML/blob/1531070587fb52e64d3ca169b9a98954f3a88074/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L2093). Double-check that the backup heating capacity is still autosized to the heating load at the design temp.

cc @lixiliu

**Comment by shorowit** [comment]
Confirmed that it's working correctly. When I raised the min compressor lockout temp from 5F to 15F in a test file, the autosized heat pump capacity decreased while the autosized backup capacity remained the same.

![image](https://github.com/NREL/OpenStudio-HPXML/assets/5861765/12a86560-fe96-4d60-9494-e7e485e1081d)

**Comment by lixiliu** [comment]
Thanks!
