### ISSUE TITLE
run_simulation.rb --help option does not work

### ISSUE THREAD

**Issue by BenjaminStuermer** [NREL/OpenStudio-HPXML#1613]
I have reproduced this issue in Mac OS 14.2.1 and in a Debian Bookworm Linux environment.

The --help option should output documentation of available options to the run_simulation.rb script. Instead, the following output is generated:

```
$ openstudio OpenStudio-HPXML/workflow/run_simulation.rb -h

Executes a ruby file
Usage: openstudio execute_ruby_script [OPTIONS] path

Positionals:
  path TEXT:FILE REQUIRED          Path to ruby file

Options:
  -h,--help                        Print this help message and exit

You can pass extra arguments after the ruby file, they will be forwarded.
```

The same output is generated if you use the --help long-form version of the option instead of -h.

**Comment by shorowit** [comment]
This was a bug introduced in OpenStudio itself (see [here](https://github.com/NREL/OpenStudio/issues/5062)). It has been fixed and should work again in the next release.

In the meantime, you will have to [look at the code](https://github.com/NREL/OpenStudio-HPXML/blob/0200043b5a9ceeb266837fed4e0fd56e2cdb60ad/workflow/run_simulation.rb#L88-L162) to see the CLI arguments.
