### ISSUE TITLE
`Get_space_temperature_schedule` fails when no heating and cooling

### ISSUE THREAD

**Issue by lixiliu** [NREL/OpenStudio-HPXML#1614]
[Get_space_temperature_schedule()](https://github.com/NREL/resstock/blob/2b0a7c51a6af71ed07fee2d3e13100c9984592cc/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb#L2724) fails when a building does not have any heating or cooling system. See error log below.

This issue came up from ResStock's [Water Heater Location PR](https://github.com/NREL/resstock/pull/1201), where we are assigning the location of shared water heaters to Conditioned Mechanical Room (i.e., `"LocationOtherHeatedSpace"`). In project_testing, we are hitting a rare building that does not have heating or cooling.

However, the in.xml file of the building does have `<HeatingSetpoint>` and `<CoolingSetpoint>` prepopulated under 
`<HVACSizingControl>`, which probably just doesn't get passed through to the measure. Maybe one solution is to pass those info in even if the HVAC systems are absent.

With @jmaguire1 's help, we tested a version of the same building but with a heating system specified and the problem goes away. Here's the buildstock containing the two buildings for testing. Building 48 fails and 49 passes, using the Water Heater Location PR branch.
[buildstock_test.csv](https://github.com/NREL/OpenStudio-HPXML/files/14301344/buildstock_test.csv)

@shorowit @joseph-robertson @afontani 

Failed log:
```
[11:08:15.365020 ERROR] [openstudio.measure.OSRunner] Optional not initialized
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:2743:in `get'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:2743:in `get_space_temperature_schedule'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:2824:in `get_space_or_schedule_from_location'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:1534:in `block in add_hot_water_and_appliances'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:1533:in `each'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:1533:in `add_hot_water_and_appliances'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:458:in `create_unit_model'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:182:in `block in run'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:174:in `each'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:174:in `each_with_index'
/Users/lliu2/Documents/GitHub/resstock4/resources/hpxml-measures/HPXMLtoOpenStudio/measure.rb:174:in `run'
```

**Comment by shorowit** [comment]
I provided a proposed solution [here](https://github.com/NREL/OpenStudio-HPXML/pull/1615/files/ccb68406302c1881a5bc068755d3dfa9c127fc45#diff-7e3f0ea19265f488ca36ab503e866994437d0b3b9443d08ec66d6b176afc3270).
