### ISSUE TITLE
BuildResidentialHPXML: add loop/coil watts for shared boiler

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/OpenStudio-HPXML#1616]
Without the ability to specify `shared_loop_watts` and/or `fan_coil_watts`, we can no longer produce valid HPXML files generated by ResStock when sampling a shared boiler.

**Comment by shorowit** [comment]
Perhaps ResStock should not use the shared boiler options? See https://github.com/NREL/resstock/issues/1139.

But yes, I agree that this is a problem. There is no way to fully describe these systems anymore. Possible solutions:
- Add the two inputs as you suggested
- Revert the previous changes where shared boilers no longer have their auxiliary energy defaulted
- Remove the ability to describe shared boilers in the BuildResHPXML measure altogether

**Comment by lixiliu** [comment]
Can we go with option 1? Not sure what option 2 is. I don't think we should remove shared boilers from BuildResHPXML measure. FWIW, 10% of the housing stock has a shared heating/cooling system and we still don't capture all the diversity we need for shared systems.

**Comment by afontani** [comment]
I would like to continue to support shared heating and cooling systems and find a way to give them the attention they need to be more representative of systems in real buildings. There are ResStock users (users of the data) who want better shared system models. The Building Performance Standards also cover these systems which the data we have is not great.

To Lixi's point, for Multi-Family units, shared HVAC systems are fairly common.
![Screenshot 2024-02-19 at 4 48 25 PM](https://github.com/NREL/OpenStudio-HPXML/assets/37630588/9e164054-38b9-482c-b207-8e25127f689f)


I take it that the `shared_loop_watts` and the `fan_coil_watts` inputs were for the energy used to manage the fans and pumps for the shared system? 

I think my preference would be to go with adding the variables to capture the energy. I think. I would rather have the ability to capture the energy.

**Comment by afontani** [comment]
After some discussion, we are leaning towards the 2nd bullet: Revert the previous changes where shared boilers no longer have their auxiliary energy defaulted.
