### ISSUE TITLE
Allow qualitative infiltration inputs (average, tight, etc.)

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1652]
Allow qualitative infiltration inputs (average, tight, etc.) using HPXML's [LeakinessDescription](https://hpxml.nrel.gov/datadictionary/3.1.0/Building/BuildingDetails/Enclosure/AirInfiltration/AirInfiltrationMeasurement/LeakinessDescription) as an alternative to quantitative blower door values.

We already have the LBNL regression coded into HEScore, so we could move it here and make it more broadly available. And for Manual J, we could implement the Table 5A defaults and update our ACCA test files accordingly.

Related to [the discussion here](https://github.com/NREL/OpenStudio-HPXML/pull/1578#discussion_r1531366554).

cc @yzhou601

**Comment by yzhou601** [comment]
It's interesting to see that [we're processing the leakiness description inputs in hpxml.rb](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hpxml.rb#L2574) but I couldn't find it being used in airflow.rb, @shorowit do you know what is the purpose that this input was added into hpxml.rb? Just want to make sure there's not unexpected impact if we start using this for sizing/simulation.

**Comment by shorowit** [comment]
@yzhou601 I'm guessing we added them to support HEScore (before HEScore moved to JSON inputs).
