### ISSUE TITLE
Wall load calculation may use wrong CLTDs

### ISSUE THREAD

**Issue by yzhou601** [NREL/OpenStudio-HPXML#1653]
Base CLTD table group numbers in Figure A12-8 are not consistent with Manual J 4A group numbers.
Figure A 12-8:
<img src="https://github.com/NREL/OpenStudio-HPXML/assets/32500275/5687fcc2-9e1e-487e-9501-e256f26cb880" width="300">
Description says the wall types are ASHRAE group numbers B-G:
<img src="https://github.com/NREL/OpenStudio-HPXML/assets/32500275/52c134b3-21b1-4a1b-a109-55a191f62a76" width="300">
And there's a mapping between Manual J 4A group numbers and ASHRAE group numbers:
<img src="https://github.com/NREL/OpenStudio-HPXML/assets/32500275/01c7faef-2bb1-44f2-aca7-340bf2fbd8f8" width="300">

While it looks like in the hvac_sizing.rb, the group number got from method [get_wall_group](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L2637-L2638) seems to be Manual J 4A group numbers, (@jonwinkler correct me if I'm wrong) and we're [directly using them (with interpolation) as indexes to base CLTD table in Figure A12-8](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hvac_sizing.rb#L714-L724). The mapping in Figure A12-12 is missing if we want to use Figure A12-8. Or we should instead use table 4B with 4A group numbers to look up CLTD values.

Related to comments: https://github.com/NREL/OpenStudio-HPXML/pull/1578#discussion_r1532507935
cc @shorowit @jonwinkler

**Comment by shorowit** [comment]
The `get_wall_group` method definitely determines Table 4A group numbers. I agree that it looks wrong. In fact, the comment in the code "intermediate wall groups were determined using linear interpolation" supports this conclusion, because if you used ASHRAE groups instead of table 4A groups with Figure A12-8 then no interpolation would be needed!

**Comment by yzhou601** [comment]
> The `get_wall_group` method definitely determines Table 4A group numbers. I agree that it looks wrong. In fact, the comment in the code "intermediate wall groups were determined using linear interpolation" supports this conclusion, because if you used ASHRAE groups instead of table 4A groups with Figure A12-8 then no interpolation would be needed!

I agree, except if there's another set of group numbers that we were not aware of. 🙅

**Comment by shorowit** [comment]
I spoke too soon. Now I think it's correct. I just noticed that the Table 4A groups sometimes map to two ASHRAE groups, so that's where the interpolation comes into play.

Let's do a quick example... Table 4A Group B maps to ASHRAE Groups F-G, where F is 31.9 and G is 38. The average is 34.95, which matches the code. Looks right.

**Comment by yzhou601** [comment]
> I spoke too soon. Now I think it's correct. I just noticed that the Table 4A groups sometimes map to two ASHRAE groups, so that's where the interpolation comes into play.
> 
> Let's do a quick example... Table 4A Group B maps to ASHRAE Groups F-G, where F is 31.9 and G is 38. The average is 34.95, which matches the code. Looks right.

Oh I now see the relationship between these two group numbers and why we handle it in this way. The 4A groups are just a reverse version of ASHRAE groups with interpolation at each middle point. The get_wall_group already put them in reverse order, where returned A group maps to G group in the ASHRAE table. Glad that this is a false alarm!
I'm closing this issue.
