### ISSUE TITLE
Geothermal fan/pump adjustment fix

### ISSUE THREAD

**Issue by jmaguire1** [NREL/OpenStudio-HPXML#1793]
From Jeff Munk when he reviewed our report on GHPs and the fan/pump adjustments:

"These are going to be pretty significant overestimates of fan power relative to the fan power incorporated into the ISO rating.  The ISO rating is meant to only account for fan power to overcome the internal static pressure of the unit (i.e., running the unit without any supply or return ductwork).  I couldn’t find where the .375 or .5 W/cfm came from in the Home Energy Score, but they are definitely high enough that they are accounting for some external static pressure.

The magnitude of the impact this has on the actual simulation results depends on how much the airflow is allowed to deviate from the 400 cfm/ton nominal value that was to convert from net to gross ratings."

When the new FY kicks off and we have an opportunity to add new GHP features, I'm going to sit down with him and talk about how we might want to change the fan power calculation here.

**Comment by shorowit** [comment]
@jmaguire1 will try to implement this for the coming release.
