### ISSUE TITLE
Neighbor shading object height not in the documentation

### ISSUE THREAD

**Issue by afontani** [NREL/OpenStudio-HPXML#1812]
Can we have a note about the neighbor shading object hight in the documentation? I was looking at the ResStock arguments `neighbor_<side>_height` and realized we default this value to "auto". The argument definition table for ResStock references the [HPXML Site](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-site) section of the documentation. The `extension/Neighbors` element defaults to not having a shading object, but does not mention the height anywhere.

I did see this line in the code: https://github.com/NREL/OpenStudio-HPXML/blob/be0d5cc4e7d3d1e000c546b2e13b1ec7b0444e18/HPXMLtoOpenStudio/resources/geometry.rb#L606

It seems that if the height is not specified, the height of the shading object is the height of the total height of the dwelling unit.

Where would be a good place to add some information?

**Comment by shorowit** [comment]
It’s documented [here](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-neighbor-buildings). Looks like the link should be changed from HPXML Site to HPXML Neighbor Buildings.
