### ISSUE TITLE
Dehumidifier documentation

### ISSUE THREAD

**Issue by lixiliu** [NREL/OpenStudio-HPXML#1832]
Current documentation does not explain how dehumidifier energy is calculated based on inputs and what schedule(s) it is using. Or perhaps a dehumidifier is modeled as a real appliance that meets the RH set point like heating/cooling?
https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#hpxml-dehumidifier

**Comment by shorowit** [comment]
Yes, it operates as needed to maintain RH setpoint for the conditioned space. We can clarify this in the docs.
