### ISSUE TITLE
Specified Height of Lower Element of Stratified Water Heater is incorrect

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio-HPXML#1847]
**HPXML to OpenStudio" workflow,  version : v1.8**
**Filename: "waterheater.rb"**

**Expected Behavior** :
When modeling a WaterHeaterStratified object, there should be a vertical height **difference** between the upper and lower elements. 
When reviewing older (v1.4 HPXML to OpenStudio) versions of the file, we see
      # height of upper and lower element based on TRNSYS assumptions for an ERWH
      h_UE = 0.733333333 * h_tank # node 4
      h_LE = 0.133333333 * h_tank # node 13

**Observed Behavior** :
 See code here: https://github.com/NREL/OpenStudio-HPXML/blob/e770f42307069ba1ed46467ddaee3866d2f70551/HPXMLtoOpenStudio/resources/waterheater.rb#L1993
The current code uses the same value when calling the method "setHeater1Height" and "setHeater2Height"

**Suggested fix**
Correct the height of the lower element of to reflect 0.133333333 * h_tank

**Comment by shorowit** [comment]
Good catch, this got messed up in a code refactor. Fixing it.
