### ISSUE TITLE
Inconsistent hourly vs sub-hourly stochastic hot water schedules

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#1890]
If I compare annual full load hours for stochastic schedules using 10-minute and 60-minute timesteps (e.g., [here](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic.csv) vs [here](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedule_files/occupancy-stochastic-10-mins.csv)), I get:

  | Full load hours (60-min timestep) | Full load hours (10-min timestep) | Difference
-- | -- | -- | --
occupants | 6689 | 6707 | 0%
lighting_interior | 2086 | 2077 | 0%
lighting_garage | 2086 | 2077 | 0%
cooking_range | 534 | 534 | 0%
dishwasher | 213 | 213 | 0%
**clothes_washer** | **134** | **105** | **22%**
clothes_dryer | 151 | 151 | 0%
ceiling_fan | 3016 | 3009 | 0%
plug_loads_other | 5388 | 5393 | 0%
plug_loads_tv | 1517 | 1505 | 1%
**hot_water_dishwasher** | **273** | **146** | **47%**
**hot_water_clothes_washer** | **346** | **154** | **56%**
**hot_water_fixtures** | **887** | **397** | **55%**
**hot_water_showers** | **380** | **142** | **63%**

As you can see, the hot water and clothes washer values are very inconsistent. (Interestingly, the dishwasher is fine?)

This is impacting the results in https://github.com/NREL/OpenStudio-HPXML/pull/1502.

@rajeee @jmaguire1 @joseph-robertson

**Comment by jmaguire1** [comment]
Good point Rajendra. This might actually be more prominent for HW use in particular, because you'll end up with events that are only a few minutes long, whereas I think most appliances you'd expect to run for at least 15-20 minutes? So the difference in the normalization factor for DHW could be a lot larger than it is for other end uses. At least I suspect that's the case.

**Comment by shorowit** [comment]
Ah, I forgot that the power design level (or peak flow rate) is not constant, but rather calculated from the desired annual energy use and number of hours in the schedule. So these schedules do seem correct, in that you'd expect higher peaks (and therefore lower schedule hours) when using sub-hourly timesteps. For other appliances (dishwashers, cooking ranges, etc.), they have long event durations at the peak, so the peak does not change between hourly and sub-hourly timesteps.

Okay, I'm satisfied here that there isn't an issue. Closing it. Thanks for the investigation and discussion on Teams, @rajeee.

Now that I understand, I'll need to revisit the unmet water heating load PR and think about whether the implementation there is correct...
