### ISSUE TITLE
Dynamically create HPXMLs

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#35]
Create an `update_hpxmls` rake task that generates all the HPXML files in the /tests dir, including all subdirectories: cfis, hvac_autosizing, etc. They are all derivatives of valid.xml. (Note that some files have the .xml.skip extension because these tests don't yet pass, but we want to include them in this process.)

Probably best to mention in the HPXML file that they were created automatically, so that developers in the future don't manually edit them. How about in the `<XMLGeneratedBy>` element?

**Comment by shorowit** [comment]
And please try to use the methods in our [XMLHelper class](https://github.com/NREL/OpenStudio-HPXML/blob/master/resources/xmlhelper.rb#L4), rather than built-in REXML, where possible. If we ever switch to a different XML library, this will make it much easier.

**Comment by joseph-robertson** [comment]
Should we wrap stuff like this (where REXML is explicitly called out) in a new XMLHelper method? https://github.com/NREL/OpenStudio-HPXML/blob/master/measure.rb#L112

**Comment by shorowit** [comment]
Yes, that would be great. Ideally we would not use REXML outside the XMLHelper class.

**Comment by joseph-robertson** [comment]
This must be nokogiri-free, correct?

**Comment by shorowit** [comment]
Correct. Use REXML (via XMLHelper class where possible; feel free to expand the methods there as needed).

**Comment by shorowit** [comment]
Defer this until we have the HPXML class in place (see ERI & HEScore GitHub issues); then use it for this effort.

**Comment by joseph-robertson** [comment]
Are we at the point where we can further talk about this?

**Comment by shorowit** [comment]
Some psuedo code:

```
def create_hpxmls
  
  hpxml_files = [ 'valid.xml',
                  'valid-appliances-washer-imef.xml',
                  'valid-foo.xml' ]
  
  hpxml_files.each do |hpxml_file|
    site_values = get_hpxml_file_site_values(hpxml_file)
    HPXML.add_site(..., **site_values) unless site_values.nil?
    
    wall_values = get_hpxml_file_wall_values(hpxml_file)
    for i in 1..n
      HPXML.add_wall(...)
    end
  end
  
end

def get_hpxml_file_site_values(hpxml_file)
  site_values = { :foo => 0,
                  :bar => "blah" }
  if hpxml_file == 'valid-wall.xml'
    site_values[:foo] = 1
    site_values[:bar] = nil
    site_values[:test] = 'whatever'
  end
  return site_values
end

def get_hpxml_file_wall_values(hpxml_file)
  wall_values = { :id => ['wall1', 'wall2'],
                  :rvalue => [13.0, 0.0] }
  return wall_values
end
```

**Comment by shorowit** [comment]
@joseph-robertson this is ready to be worked on.
