### ISSUE TITLE
Use Ruby 2.1+ required keyword arguments

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#36]
Ruby 2.0 allows [keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments) so as to prevent issues related to the order of arguments passed. Even better, ruby 2.1 allows [required keyword arguments](https://robots.thoughtbot.com/ruby-2-keyword-arguments#required-keyword-arguments). 

Refactor methods in the resource files to use required keyword arguments (though optional arguments will remain optional keyword arguments).

**Comment by shorowit** [comment]
See openstudio-standards for some examples where they've done this.

**Comment by joseph-robertson** [comment]
How do you feel about this example?

Method:
```  
def get_abs_azimuth(azimuth_type:, relative_azimuth:, building_orientation:, offset: 180.0)
    azimuth = nil
    if azimuth_type == Constants.CoordRelative
      azimuth = relative_azimuth + building_orientation + offset
    elsif azimuth_type == Constants.CoordAbsolute
      azimuth = relative_azimuth + offset
    end

    # Ensure azimuth is >=0 and <=360
    while azimuth < 0.0
      azimuth += 360.0
    end

    while azimuth >= 360.0
      azimuth -= 360.0
    end

    return azimuth
  end
```

Call:
```
get_abs_azimuth(building_orientation: 'north', azimuth_type: 'relative', relative_azimuth: 'true')
```

In openstudio-standards, the required arguments are still positional. Here they are not, since they use the trailing colon.

**Comment by shorowit** [comment]
👍 👍 👍 
Looks great to me.
