### ISSUE TITLE
Heating Electric Energy (monthly and annual) results are suspect, when comparing 1-speed, 2-speed and 4-speed ASHP HVAC using hpxml v0.9 workflow

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio-HPXML#396]
Issue overview
--------------
Monthly and annual (Heating, Electric) Energy dos not appear to trend as expected when comparing Carrier AHRI Performance Data for 1-speed, 2 speed and 4 speed ASHP, for an all-electric 1 story home with a conditioned basement, in Atlanta GA. 

## Current Behavior
1) Using hpxml-OS measure (from release v0.9.0) to compare (3) different Three ton (hard sized) ASHP (1 stage, 2 stage and variable Speed), for HVAC system comparison and savings analysis only, for a 2200 sqft home in Atlanta GA.

2) Using Carrier published AHRI performance (PDF files attached below) which describe the necessary hpxml file input parameters describing heating performance (Heating Capacities at 47F, 17F, HSPF, and presence and size of of electric backup heat) for the three different ASHP scenarios   

3) All other elements and attributes of the (3) hpxml files (attached), are held constant.  

4) When reviewing monthly reports (using OS the reporting measure, monthly overview for electric consumption is kWH) of the (Heating Electric) Energy are compared. T he **1 stage ASHP significantly outperforms** both the 2 stage and 4 stage AHSP.  This is unexpected.  See spreadsheet for summary of review

[Carrier 1 Speed 25HCE4-09PD.pdf](https://github.com/NREL/OpenStudio-HPXML/files/4663387/Carrier.1.Speed.25HCE4-09PD.pdf)
[Carrier 2 Speed 25HNB6-9PD.pdf](https://github.com/NREL/OpenStudio-HPXML/files/4663388/Carrier.2.Speed.25HNB6-9PD.pdf)
[Carrier 4-Speed 25VNA4-02PD.pdf](https://github.com/NREL/OpenStudio-HPXML/files/4663390/Carrier.4-Speed.25VNA4-02PD.pdf)

[ashp_hpxml_files.zip](https://github.com/NREL/OpenStudio-HPXML/files/4663397/ashp_hpxml_files.zip)
[osm_files.zip](https://github.com/NREL/OpenStudio-HPXML/files/4663403/osm_files.zip)

## Expected Behavior
1) It is expected that (using the HPXML->to OS v9.0) workflow), holding all other hpxml inputs for a given home constant except the inputs needed to describe ASHP **Heating energy**, that a (**3 Ton, SEER 17, HSPF 9.5 Carrier Model 25HNB6 Infinity 2-Stage Heat Pump**) would outperform a (**3 Ton SEER 14 HSPF 8.2 Carrier Model 25HCE4 Comfort 14 Single Stage Heat Pump**). This is not what is observed. 

2) It is expected that (using the HPXML->to OS v9.0) workflow), holding all other hpxml inputs constant except the inputs needed to describe ASHP **Heating 
energy**, that a (**3 Ton, SEER 22, HSPF 11.5 (Carrier INFINITY® VARIABLE SPEED HEAT PUMP WITH GREENSPEED™ INTELLIGENCE**)  would outperform a (**3 Ton SEER 14 HSPF 8.2 Carrier Model 25HCE4 Comfort 14 Single Stage Heat Pump**). This is not what is observed. 

## Steps to Reproduce

Drive .osm model generation using hpxml->OS measure (v0.9.0 release) using hpxml files proved in zipfile

a) 'base' home with 3 Ton SEER 14 HSPF 8.2, 1-stage heat pump described
b) 'base' home with 3 Ton, SEER 17, HSPF 9.5, 2-stage heat pump described 
c) 'base' home with 3 Ton, SEER 22, HSPF 11.5 Variable Speed heat pump described 

** Note that resulting os models, from executing the measure, have also been provided in an attached zipfile)  

Review "Heating Electric" Time Series and Annual end-use values, using OS Results report, DVIEW, etc.  Note a spreadsheet detailing these comparisons has been attached. 

[for_ASHP_github_issue.xlsx](https://github.com/NREL/OpenStudio-HPXML/files/4663462/for_ASHP_github_issue.xlsx)
  
## Possible Solution
Issue is potentially related to the use of improperly developed heating EIR performance curves associated with the Multispeed DX Heating Coil object . 

Because unexpected performance "gaps" between Heating-Electric appear larger under lower OA temp conditions, it may be that the discrepancy relates to how (EIR as a function of temperature) curves are being developed, when multi-speed equipment is represented. 

### Environment
Windows 10, 64 Bit. 
OpenStudio Release 1.0.0 build number 6914d4F590
Using hpxml->OS measure v9.0.0 release 

### Context
The ability to **not be able to indicate a realistic savings potential** of (heating, electric) 'savings' associated with installing a (multispeed or 2-speed) heat pump (as compared to a single speed stage heatpump) is causing credibility issues with our client. The client has expressed doubt of the results being generated, and these results cannot easily be explained away, even by technical staff who understand that energy modeling requires abstractions to be made. The issue is that simpler energy estimating methods used by the client (legacy calculation tools using older physics engines such as DOE2.x, custom spreadsheets, etc.) indicate that (heating electric energy) savings are available when multispeed ASHP equipment is installed, in the Atlanta climate. We need to be able to explain why our "hpxml driven" analysis shows otherwise, or correct mistakes made, in our analysis.

**Comment by shorowit** [comment]
@chrisbalbach The provided HPXML files do not run in the v0.9 release, as they contain some HPXML lighting changes (and maybe others?) that were made _after_ the v0.9 release. So this either means the files were run using some commit from the master branch or you provided the wrong files. Can you clarify?

**Comment by shorowit** [comment]
Also, the SEER_14_1_spd_hp.xml and SEER_17_2_spd_hp.xml files have lots of differences between them: conditioned floor area, climate zone, windows, water heaters, ....

**Comment by chrisbalbach** [comment]
Scott:

Thank you for pointing out some inconsistencies in the analysis submitted above. The analysis has been redone, beginning with a sample hpxml named "base-foundation-vented-crawlspace.xml" file taken from the samples folder that is included in the 0.9 release, workflow/samples directory. 

This sample hpxml file was selected because it represents a home with a crawlspace (the client's comparative OS v2.8 .osm model has this condition.) This file was then modified to closely resemble the OS 2.8.1 home (adjusting R values and areas to reflect the values in the v2.8.0 .osm, etc).

Subsequently, this file was cloned three times, where for each clone, hpxml snippets representing 1 speed, 2 speed and 4 speed ASHP properties (from Carrier published AHRI data) were inserted. 

Next, the hpxml files (after being diffed to confirm no changes except ASHP HVAC related info) were pushed through the "hpxml->os"  measure bundled with the 0.9 hpxml workflow release. 

The monthly electric usage results from these (3) hpxml files have been updated in the 'corrections' tab of the attached spreadsheet - please ignore results on other tabs. 

While energy savings from a the variable speed unit appears to be behaving as expected, we still need to be able to explain how the heating and cooling energy associated with a (higher SEER and HSPF) two speed ASHP unit uses ~ `0% more heating and cooling energy then a single stage ASHP of lower SEER and HSPF,  using Atlanta weather...

![image](https://user-images.githubusercontent.com/5746765/82601282-50fa0000-9b7d-11ea-9c09-ec6c2da38a57.png)

Files Attached:

1) zip file of (3) hpxml files
2) xlsx sheet containing summary charts. 

[New_ASHP_HPXML.zip](https://github.com/NREL/OpenStudio-HPXML/files/4664507/New_ASHP_HPXML.zip)

[for_ASHP_github_issue.xlsx](https://github.com/NREL/OpenStudio-HPXML/files/4664529/for_ASHP_github_issue.xlsx)

**Comment by shorowit** [comment]
After correcting our [HP defrost control strategy](https://github.com/NREL/OpenStudio-HPXML/pull/403/files#diff-f865e7b10a878fbe87058db74b4a5c0eR2982), I re-ran the files and the trend looks better.
