### ISSUE TITLE
Reducing leakage to zero for ducts located in a conditioned basement impacts heating energy use

### ISSUE THREAD

**Issue by eomere** [NREL/OpenStudio-HPXML#402]
My simulations reveal that a building with ducts in the conditioned basement has decreased heating energy usage when when I seal the ducts (i.e. set duct leakage value to 0.01). I feel that this is a bug, because the ducts are in a conditioned basement. Reducing duct leakage should not affect heating energy usage.

Please see the corresponding xmls: 
https://www.dropbox.com/s/mjnkxuk37z6t6x7/baseline.xml?dl=0

https://www.dropbox.com/s/uy0cn183u8oacdg/baseline%20with%20no%20duct%20leakage.xml?dl=0

**Comment by shorowit** [comment]
I can see how this might be confusing, but it is behaving as intended. Note that the duct leakage input is leakage _to the outside_ (i.e., outside conditioned space). If your ducts are entirely within conditioned space, then the duct leakage to the outside should be set to zero. If the ducts are entirely within conditioned space but you provide non-zero duct leakage to the outside, we treat the duct leakage as heat literally lost to the ambient environment. 

This functionality was specifically requested from a third-party software developer. This is how they described it: 

> Regarding Leakage to the Outside (LtO), it is possible from the duct test protocols to measure duct leakage to outside when all equipment and ductwork is nominally in conditioned space.  The reality is that sometimes those “conditioned spaces” leak.  In a common example, ducts may be in  floor cavities which have leaky rims; the rim leakage is both building leakage (but probably poorly captured by the blower door test) and LtO for the ducts leaking in that space.

I'm open to ideas on how to make this more clear. For example, we could specifically call this out in our documentation or add a warning (perhaps if the LtO value is above a certain level).

**Comment by eomere** [comment]
Thank you for the quick response Scott! That was helpful.
