### ISSUE TITLE
Add default mappings for all existing wall siding options

### ISSUE THREAD

**Issue by pegdeploy** [NREL/OpenStudio-HPXML#575]
It doesn't make sense to restrict the HPXML to use only a limited selection, when reasonable mappings can be made to the currently allowed options. This requires existing HPXML tools to either make a special version for OpenStudio or lose accuracy in their that is potentially important in non-modeling applications.

**Comment by GamalielL** [comment]
Oops.  Accidentally submitted this from the wrong account.

**Comment by shorowit** [comment]
Need to allow more `RoofType` (material) options as well.
