### ISSUE TITLE
Double-check use of HeatingSystem/HeatingCapacity

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#624]
The value in HPXML is an **input** heating capacity per the [HPXML spec](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatingSystem/HeatingCapacity). Check that we are using input vs output capacity appropriately when:
- [x] Translating to E+ when the HPXML has a heating capacity specified
- [x] Writing auto-sized defaults when the HPXML has no heating capacity specified

Also:
- [x] Update HPXML schema if needed
- [x] Update documentation if needed

Cooling systems and heat pumps should be fine.

FYI @ejhw @joseph-robertson

**Comment by ejhw** [comment]
Thanks @shorowit. Can we edit the spec for cooling capacity to add "output" to make it more explicit? https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/CoolingSystem/CoolingCapacity

**Comment by shorowit** [comment]
I'm looking into this and here's what I found so far:
1. For a furnace the [AHRI ratings](https://www.ahridirectory.org/NewSearch?programId=64&searchTypeId=3) include "Input Rating" and "Output Heating Capacity".
2. The inputs in two software tools I checked (BEopt and REM) ask for _output_ heating capacity. 
3. Our HVAC sizing code treats the value in the HPXML file as an _output_ heating capacity; indeed we get the same autosized heating capacity in the HPXML regardless of AFUE.
4. EnergyPlus is expecting _output_ heating capacity.

So all the BEM uses of HPXML are consistently treating it as output heating capacity despite the HPXML definition.

I think the issue is fundamentally that HPXML doesn't have separate inputs for _output_ vs _input_. It's probably using input heating capacity because it started as an audit standard before we began using it for BEM purposes. The ideal solution that aligns with AHRI would be to create a new `HeatingInputRating` element in HPXML and then change the definition for `HeatingCapacity` to be _output_. That is not technically a breaking change, but would require some HPXML use cases to update how they use it.

**Comment by nmerket** [comment]
@shorowit's proposal would be problematic in that it changes the meaning of the data element, so you could run into the situation where someone would submit a file and missed that they should now be storing that field in `HeatingInputRating`, but it would fail silently.

**Comment by shorowit** [comment]
Proposed the HPXML change [here](https://github.com/hpxmlwg/hpxml/pull/249). We'll see what the HPXML Working Group thinks. For now, treat the HPXML element as _output_ heating capacity.
