### ISSUE TITLE
Operational Calculation (occupancy-based loads)

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#644]
Allow a user to do an operational, instead of asset, calculation through a new HPXML input field. For example, we could adopt the [ResStock occupancy adjustments](https://github.com/NREL/resstock/blob/a5a60718ec58bfbbc3c04c186ca30155184c106d/measures/ResStockArguments/measure.rb#L413-L424) for appliances and hot water when an operational calculation is to be performed.

**Comment by shorowit** [comment]
I suggest a new high-level input that is called CalculationType with choices of "asset" and "operational". If asset is chosen, usage multipliers not provided continue to default to 1.0. If operational is chosen, usage multipliers not provided are calculated as there are for ResStock. I suggest we make this a required input (breaking change) so that users are forced to specify which situation they want.

**Comment by shorowit** [comment]
I think it should be a field in the HPXML file.

**Comment by joseph-robertson** [comment]
> I suggest a new high-level input that is called `OccupancyCalculationType` with choices of "asset" and "operational". If asset is chosen, usage multipliers not provided continue to default to 1.0 (meaning energy use is calculated based on floor area, # bedrooms, etc. as before). If operational is chosen, usage multipliers not provided are calculated as they are for ResStock. I suggest we make this a required input (breaking change) so that users are forced to specify which situation they want.

For ResStock, even usage multipliers that are provided get the occupancy adjustments.

**Comment by shorowit** [comment]
I see. I proposed this approach because we can't adjust the provided usage multipliers -- I could see situations where someone runs an HPXML, the in.xml has adjusted values, and then they run the in.xml and the values get adjusted a _second_ time. That wouldn't be good.

So how about we add `OccupancyUsageMultiplier` inputs, which are used in conjunction with the existing `UsageMultiplier` inputs?

**Comment by shorowit** [comment]
Or `UsageMultiplier2`?

**Comment by joseph-robertson** [comment]
Would `OperationalUsageMultiplier` be more clear?

An alternative could be to not store `OccupancyCalculationType` on the HPXML, and instead perform the calculations from `BuildResidentialHPXML`.

**Comment by shorowit** [comment]
Good suggestion. We could go with that for now and see if anyone has feedback.

I want these default occupancy multipliers to be available to tools that aren't using the BuildResHPXML measure. So the calculations should be done as part of the HPXMLtoOS defaulting.

**Comment by joseph-robertson** [comment]
Should:
- [ ] we only default `OperationalUsageMultiplier` if `OccupancyCalculationType=operational`?
- [ ] update schema to prevent any `OperationalUsageMultiplier` when `OccupancyCalculationType=asset`?

**Comment by shorowit** [comment]
Your questions make me think that the choice of `OperationalUsageMultiplier` is making things more complicated than necessary. How about we go back to `OccupancyUsageMultiplier` and, if not provided, it defaults to 1.0 for asset and X for operational. Total energy use = energy use x UsageMultiplier x OccupancyUsageMultiplier. Simple.

**Comment by shorowit** [comment]
Or.... maybe we should simplify this even further and not even have a second usage multiplier. Just automatically apply the operational multiplier behinds the scene when `operational` is chosen and document how it affects the end uses. Then there will be no confusion about the two usage multipliers (that are both related to occupants).

**Comment by joseph-robertson** [comment]
But wouldn't it be nice to store the calculated operational multiplier in the HPXML file?

**Comment by joseph-robertson** [comment]
Or maybe I don't know what you mean by "document it"?

**Comment by shorowit** [comment]
Document it in the documentation.

I would be okay with having the multiplier show up in the in.xml, but I mostly want to avoid it being a user input. If the user needs to adjust the usage for occupancy, that's what the existing UsageMultiplier is for. It gets too confusing to have two separate inputs.
