### ISSUE TITLE
Simplify inputs for (ductless) fan coils

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#658]
- [ ] Allow `DuctLeakageMeasurement` to not be specified for ductless fan coil systems
- [ ] Remove the `NumberofReturnRegisters` from the base-bldgtype-multifamily-shared-boiler-chiller-fan-coil.xml sample file.

**Comment by joseph-robertson** [comment]
Remove `NumberofReturnRegisters` from base-bldgtype-multifamily-shared-boiler-only-fan-coil.xml, too.
