### ISSUE TITLE
New Feature Request: Provide ability for HPXML workflow users to configure lengths of heating/cooling seasons 

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/OpenStudio-HPXML#700]
**Current Behavior:**
Current HPXML based workflows assume both heating and cooling season lengths to be 12 months in duration (Jan - Dec)

**Desired Behavior:**
Provide defaulted heating and cooling season lengths of 12 months but provide an override mechanism where users can specify the starting and ending months of the heating and cooling seasons, or to use the algorithm defined in the Building America 2014 Simulation House Protocols to parse the weather file associated with the model to programmatically determine whether a month is heating only, cooling only, heating and cooling, or neither. Alternatively, improve the published algorithm for automatically determining the month "status" to reduce the effect of missing "swing" months, etc. . 

**Rationale:** 
In general, this new feature can be leveraged to improve modeling accuracy of predicting energy usage by better representing real world behavior of heating/cooling equipment in multifamily buildings. Providing the ability for users to set/define heating and cooling season lengths will improve the ability for users to match the behavior of heating and cooling equipment as observed in actual multifamily buildings, where central heating and cooling equipment are disabled for maintenance/service, etc during non-seasonal periods of use. For example, many cities such as NYC, mandate lengths of heating seasons in rental properties. For NYC, it is from October 1 to May 31st (regardless of weather conditions). 

See https://streeteasy.com/blog/nyc-renters-rights-heat-hot-water/

In these scenarios, many multifamily building owners, where heat expenses are provided by the owner, will turn on central heating systems as late as possible and turn off central heating systems as early as possible, to conserve fuel costs.

Enabling seasonal lockout of heating/cooling equipment also improves the ability for the model to predict off season 'demand'  by not allowing equipment (compressors, fans, pumps, etc) to operate and contribute to 'false positive' estimates of equipment demand that would not be allowed to start during the disabled period. 

**Potential Implementation Strategies:**
The impact of implementing htg/clg equipment seasonal lockout via extreme thermostat settings (i.e. zone htg setpoint = 20F in non-heating month, zone cooling setpoint = 105F in non-cooling month) should have no impact on reported district heating / cooling energy use associated with 'unmet hours'. 
Previous BeOPT measures (archived, no longer publicly available) exposed 3 arguments for accomplishing the desired feature:

1)     clg_t_stat_use_auto_season 
2)     hlg_t_stat_use_auto_season
3)     clg_t_stat_season_start_month
4)     htg_t_stat_season_start_month
5)     clg_t_stat_season_end_month
6)     htg_t_stat_season_end_month

A preferred solution would be incorporate these data elements into the HPXML 'controls' element, using extension elements if necessary. 
An alternative solution would be to include these arguments in the BuildResHPXML measure
An optimal solution would incorporate both, providing the most flexibility for users to generate seasonal lockouts, if needed. . 

**Systems / Workflows affected**
All HPXML based workflows using the "HPXML to OpenStudio" measure.

**Comment by shorowit** [comment]
I would suggest we expose the inputs as start/end **dates** instead of **months**.

**Comment by chrisbalbach** [comment]
I would agree that implementing by dates (as opposed to calendar months) would be a more generalized (and thus more useful) implementation of the requested feature. It's worthy of note that some jurisdictions do use a mid month date (September 15th, etc.) as a threshold compliance date as well. We have historically post processed model output using entire calendar months, mostly out of convenience, but that would still be possible with this implementation.

Only issue that comes to mind, with using dates instead or whole cloth months, is dealing with the **inevitable** leap year use-case. I'm not sure how that would work - Have you considered a way to handle that ?

**Comment by shorowit** [comment]
Hmm. Can you clarify the challenge related to handling leap years? I'm not immediately seeing the issue.

**Comment by chrisbalbach** [comment]
Maybe is will be handled correctly in the approach, but it seems like there would need to be support for defining a heating season ending date of Feb 29, regardless of any actual Feb 29 information in an accompanying weather file (AMY/TMY/etc).
I suppose having a heating season end (or cooling season start) on Feb 29, seems unlikely, at least in North America. I just remember in the past, with TREAT/SUNREL, struggling with this with some users who were cooking their own TMY weather files. .. EnergyPlus probably handles it much better, I have not yet exercised it.
