### ISSUE TITLE
Timestamps on outputs are weird

### ISSUE THREAD

**Issue by nmerket** [NREL/OpenStudio-HPXML#721]
The timestamps on the timeseries outputs are a little wonky. They seem to show the timestamp _after_ the one we want. For example when I ask for daily I get

```json
{
  "Time": [
    "2007/01/02 00:00:00",
    "2007/01/03 00:00:00",
    "2007/01/04 00:00:00",
    "2007/01/05 00:00:00",
    "2007/01/06 00:00:00",
    "2007/01/07 00:00:00",
    "2007/01/08 00:00:00",
```

And when I run monthly I get 

```json
{
  "Time": [
    "2007/02/01 00:00:00",
    "2007/03/01 00:00:00",
    "2007/04/01 00:00:00",
    "2007/05/01 00:00:00",
    "2007/06/01 00:00:00",
    "2007/07/01 00:00:00",
    "2007/08/01 00:00:00",
    "2007/09/01 00:00:00",
    "2007/10/01 00:00:00",
    "2007/11/01 00:00:00",
    "2007/12/01 00:00:00",
    "2008/01/01 00:00:00"
  ],
```

**Comment by shorowit** [comment]
We simply report the timestamps from EnergyPlus itself, which indeed use the end-of-time convention. (Though it actually uses the [24:00 convention, which most everyone hates](https://github.com/NREL/EnergyPlus/issues/5360).)

![image](https://user-images.githubusercontent.com/5861765/115627363-2009da00-a2bc-11eb-8f26-9a60cfdca37a.png)

If you really wanted to address this, you could [update our reporting measure code here](https://github.com/NREL/OpenStudio-HPXML/blob/5d9bb249bb5d20ae7c5f059291de6afbe231832f/SimulationOutputReport/measure.rb#L442-L465).

**Comment by shorowit** [comment]
- [ ] Add an optional argument for our reporting measure that specifies whether to use start-of-time or end-of-time convention. Consider defaulting to start-of-time?
- [ ] Double-check what convention DView expects when the `dview_csv` format is requested. The above argument should not apply to this case.
- [ ] Update the documentation
