### ISSUE TITLE
Heat pump backup heater smart recovery

### ISSUE THREAD

**Issue by yzhou601** [NREL/OpenStudio-HPXML#772]
Currently, backup heater will be turned on to help recover zone temperature during a setpoint change, more specifically when setpoint changes from lower temperature to higher temperature. This will cause systems to be less energy efficient. In reality, many thermostats like Nest and Ecobee, etc. already have smart recovery. It's worthwhile to include an option to see how much smart recovery can impact energy results. From Jon, "we were monitoring homes in New Orleans with ASHPs and stupid setback recovery. in response to their high utility bills, homeowners set back even more! resulting in this positive feedback look because the more they setback the temperature, the higher the bills due to the backup being used to recover. " Besides, it is more valuable to have the capability of modeling the smart recovery for geb analysis.
@jonwinkler @shorowit @jmaguire1 @benpolly1

**Comment by jonwinkler** [comment]
@jmaguire1 If it's a complicated feature to implement, perhaps it's best to hold off until you hear of someone interested in running that type of analysis.

**Comment by shorowit** [comment]
@ejhw's comment [here](https://github.com/NREL/OpenStudio-HPXML/issues/869#issuecomment-933670412) is related to this.

**Comment by shorowit** [comment]
It seems like we could start simple with a `HeatPump/BackupHeatingLockoutTemperature` input that is fed directly into the [Unitary System's Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-unitary-equipment.html#field-maximum-outdoor-dry-bulb-temperature-for-supplemental-heater-operation) input. Any thoughts on that, @jmaguire1 @yzhou601 @jonwinkler @ejhw?

**Comment by shorowit** [comment]
Apparently we already have a default lockout temperature of 40 F implemented.
- ResStock pre-HPXML [here](https://github.com/NREL/resstock/blob/bb44e6ee28fea8766a6d17cfc35c8e67b9fec58c/resources/measures/HPXMLtoOpenStudio/resources/hvac.rb#L642)
- OS-HPXML [here](https://github.com/NREL/OpenStudio-HPXML/blob/574b38941fd72164eebc8dcfe493eafc6539b4e1/HPXMLtoOpenStudio/resources/hvac.rb#L3586)

If we added an HPXML input, it's not clear to me what the default should be. No lockout temperature? Or a lockout temperature of 40F?

**Comment by ejhw** [comment]
Interesting. I think a default of 40F probably makes sense based on the [WSU article](https://www.energy.wsu.edu/documents/AHT_Electric%20Heat%20Lock%20Out%20on%20Heat%20Pumps%20(2).pdf). cc @afontani for EULP calibration awareness.

32 or 35 F would be an EE measure and smart recovery would be an even better EE measure. 

Still lots of resistance heat used below 40F in Dallas, TX when there is night setback: 
![image](https://user-images.githubusercontent.com/1276021/167224754-a1f0998b-6351-4e0e-b45b-d494882b2bc8.png)
[source](https://www.sciencedirect.com/science/article/pii/S0306261921005559)

**Comment by shorowit** [comment]
For what it's worth, [here's another article](https://www.howtolookatahouse.com/Blog/Entries/2020/11/what-is-an-electric-heat-lock-out-on-a-heat-pump.html) which says 35F is a typical value.

**Comment by shorowit** [comment]
I think this has been addressed. Reopen if there is more that needs to be considered/implemented.
