### ISSUE TITLE
Allow partition wall & furniture mass inputs

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#777]
Allow additional inputs to characterize, e.g., interior partition wall mass and furniture mass.

Currently we assume that:
1. The interior partition wall mass area (both sides) equals the conditioned floor area and is wood frame construction with 1/2" drywall.
2. The amount of furniture mass is 8 lb/ft2 of conditioned floor area.

**Comment by yzhou601** [comment]
@shorowit Are the conductivity values in above table correct? It looks so small compared against others in [material.rb](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/materials.rb#L323-L358) .
