### ISSUE TITLE
Create `BuildResidentialScheduleFile` measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#814]
Pull code out of the BuildResidentialHPXML measure and make its own measure. That will allow the schedule generator to be used in additional workflows (i.e., that do not include the BuildResidentialHPXML measure).

### BuildResidentialScheduleFile measure
- Creates schedule csv file and adds path to HPXML file.
- Arguments:
  - `hpxml_path` (used to determine state, timestep, is_leap_year)
  - `schedules_type` ("smooth" or "stochastic")
  - `vacancy_period` (current argument description in BuildResHPXML measure says it only applies if `schedules_type` is "stochastic", but doesn't it also apply if "smooth"?)
  - `random_seed`
  - `output_csv_path`
- (For ResStock-HPXML it might make sense to include these arguments in the `BuildExistingModel` measure, except for `schedules_type` and `vacancy_period` since they are sampled.)

### BuildResidentialHPXML measure
- Largely unchanged other than modifications to a few arguments.
- Arguments:
  - add `state` (optional input; if defaulted, uses EPW state as currently the case. EPW may not be in the same state as the house location, that's why we should add an explicit input); resstock develop passes sampled `state` to generator measure
  - remove `schedules_type`
  - remove `schedules_path`
  - remove `schedules_vacancy_period`
  - remove `schedules_random_seed`

## Workflows

This would support multiple workflows that want to use more detailed and/or stochastic schedules:
1. BuildResidentialHPXML  -> BuildResidentialScheduleFile  -> HPXMLtoOpenStudio
2. third-party software tool -> HPXML file -> BuildResidentialScheduleFile  -> HPXMLtoOpenStudio
3. third-party software tool -> HPXML file & schedule CSV -> HPXMLtoOpenStudio

Questions:
* Should we have BuildResidentialScheduleFile update the `SchedulesFilePath` field of the hpxml file? Otherwise, you could run into an issue where your hpxml file doesn't point to the schedule file that you generate. The alternative might be to have a `output_csv_path` argument to HPXMLtoOpenStudio.
* Results are not identical between when not applying BuildResidentialScheduleFile and when applying it with `schedules_type=smooth`; should they be?

**Comment by joseph-robertson** [comment]
We'll create `build-res-sch-file` from `master`.
Will need unit testing.
New arguments for `run_simulation.rb` for using the new measure? (i.e., `schedules_type`)

Branch from `build-res-hpxml-v3` with removals? Since there is more than just removing going on, we should probably do this in a branch.
Will need to update tests.
