### ISSUE TITLE
Detailed HVAC setpoints (GEB)

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#844]
Allow using an 8760 (or more frequent if running at shorter timesteps) schedule for heating/cooling setpoints. Similar to water heater setpoint capability in https://github.com/NREL/OpenStudio-HPXML/issues/635. Might need to be careful about other parts of the code (e.g., natural ventilation, ceiling fan temperature offset, etc.) that are based on setpoints.

**Comment by joseph-robertson** [comment]
@shorowit Can you think of, or point me to, other parts of the code that are based on setpoints?

**Comment by shorowit** [comment]
Here are the two that kind to mind:
- [Ceiling fan](https://github.com/NREL/OpenStudio-HPXML/blob/58bccc6420c112b413bd63c65b85bc09f48ff710/HPXMLtoOpenStudio/resources/hvac.rb#L849-L861)
- [Natural ventilation](https://github.com/NREL/OpenStudio-HPXML/blob/58bccc6420c112b413bd63c65b85bc09f48ff710/HPXMLtoOpenStudio/resources/airflow.rb#L374-L378) (seems like it will automatically handle any changes you make because it does the calculation using EMS sensors on the setpoint schedules?)

**Comment by ejhw** [comment]
Scott brought up the fact that this would result in behavior that is like a smart thermostat (different setpoint schedule every day) but not programmable thermostats (same setpoint schedule every day or weekdays/weekends). We decided to proceed with developing this as originally planned, which a setpoint schedule that varies day-to-day, but we agreed said that it might be worth exploring ways to convert the 8760 sleep schedule to a repeating 24 hr (or weekday/weekend) schedule that would be more like an occupancy-sensing smart thermostat.

cc @ekpresent
