### ISSUE TITLE
Support `HeatPump/BackupSystem`

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#869]
Currently we allow three heat pump backup options:
1. **Sequential operation**. Use the `HeatPump/BackupFoo` elements w/o `BackupHeatingSwitchoverTemperature`. For each hour in the simulation, backup heat will be available if the heat pump capacity is insufficient to maintain the setpoint. Typically the `FractionHeatLoadServed` of the heat pump is 1, meaning that the heat pump (including its backup heat) will meet 100% of the heating load. The heat pump distribution system and blower fan power applies to the backup heat as well. See the base-hvac-air-to-air-heat-pump-1-speed.xml sample file for an example of a heat pump with built-in electric resistance backup.
2. **Binary operation**. Use the `HeatPump/BackupFoo` elements w/ `BackupHeatingSwitchoverTemperature`. For each hour where the outdoor temperature is above this switchover temperature, the heat pump will operate, otherwise the backup heating will operate. Typically the `FractionHeatLoadServed` of the heat pump is 1, meaning that the heat pump (including its backup heat) will meet 100% of the heating load. The heat pump distribution system and blower fan power applies to the backup heat as well. See the base-hvac-autosize-dual-fuel-air-to-air-heat-pump-1-speed.xml sample file for an example of a dual fuel heat pump with a backup furnace.
3. **Parallel operation**. Use a standalone `HeatingSystem` element. For each hour, both the heat pump and heating system will operate to meet their respective `FractionHeatLoadServed`.

Since options 1 and 2 result in the distribution system and blower fan power applying to the backup heat, they are useful for built-in electric resistance or a furnace as backup, but not e.g. a boiler or electric baseboard as backup. We should allow [`HeatPump/BackupSystem`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/BackupSystem) instead of `HeatPump/BackupFoo` elements for options 1 and 2 to handle these additional scenarios. We should use the [`HeatPump/BackupType`](https://hpxml.nrel.gov/datadictionary/3.0.0/Building/BuildingDetails/Systems/HVAC/HVACPlant/HeatPump/BackupType) element to determine which situation we are in.

**Comment by ejhw** [comment]
Under #1, would we be able to support a lockout temperature for electric resistance backup? Dave made me aware of this and it can be significant for recovery from setback. See http://www.energy.wsu.edu/documents/AHT_Electric%20Heat%20Lock%20Out%20on%20Heat%20Pumps%20%282%29.pdf

**Comment by chrisbalbach** [comment]
I see two issues that need considering - **one** is how to control a 'hard sized' ccASHP object to match what is happening 'in the field' and the **second** is how to properly generate 'autosize' ccASHP DX htg coil capacity (under what conditions..?) 

Relating to the 1st issue, while operating a ccASHP and setting a heating T-stat setback during cold temps **is not a recommended behavior**, many smart T-stats (NEST, etc.) have optional modes for trying to keep the heat pump 'system' operating efficiently.  See https://support.google.com/googlenest/answer/9248719?hl=en#zippy=%2Clearn-more-about-heat-pump-balance-details%2Chow-to-change-heat-pump-balance-settings

Would it be possible to **creatively emulate** the "max comfort", "max savings", "balanced" and "off" modes described in the NEST site? ECOBEE does something similar, seemingly driven by a 'run time per degree day' user-input into their proprietary control algorithm. 

As far as I can tell, if we had the heating balance point of the building (a proxy may be available via data provided by the Manual J like calculations, w/o having to run a full simulation), then a more complex but accurate EMS program may be able to react to the simulated rate of change from the prescribed balance point, to try to stay in heat pump mode by maxing out delivered heat **before** the simulated need to max out actually occurs, (w/o resorting to strip backup), or something like that.  

Relating to the 2nd issue, for ccASHP w/ backup heat sources and trying to accurately 'predict' electric demand , we have some concerns on how auto-sized heat pump capacities (Using Manual J like methods which use a prescribed indoor heating temperature for heat pump sizing) do not account for the capacity needed if/when a homeowner uses set-back controls with their ccASHP.

**Comment by shorowit** [comment]
@chrisbalbach Regarding the second item, it sounds like you should provide that feedback to ACCA.
