### ISSUE TITLE
Battery storage follow-up

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#906]
- [x] Remove[ battery rated power output warning](https://github.com/NREL/OpenStudio-HPXML/pull/884/commits/4e2ecd8ef62bbcc40d77e51e729ed058ba91ba0c) when bugfix for NREL/OpenStudio#4495 is available in a future OpenStudio release.
- [x] Use HPXML's `UsableCapacity` field as an optional input https://github.com/NREL/OpenStudio-HPXML/pull/998
- [x] Dispatch strategy for battery with no on-site generation https://github.com/NREL/OpenStudio-HPXML/pull/1142
- [x] Additional dispatch strategies for battery with on-site generation https://github.com/NREL/OpenStudio-HPXML/pull/1142
- [x] Separate battery and PV outputs (from [here](https://github.com/NREL/OpenStudio-HPXML/issues/897)) https://github.com/NREL/OpenStudio-HPXML/pull/1142
- [x] Add a resilience metric like "Average Resiliency Hours" (see description below) https://github.com/NREL/OpenStudio-HPXML/pull/1212

**Comment by jmaguire1** [comment]
Notes from 7/12/22 meeting (Jeff/Joe/Ben):

- Charging/discharging off a schedule is definitely possible, Jeff sent Joe an example file.
- Joe thinks it won't be a huge lift to implement.
- It's not easy to combine charging/discharging schedules into a single schedule. A combined schedule would avoid situations where charging and discharging overlap, but user experience won't be substantially worse. Tentatively planning on just implementing two separate schedules.
- Jeff to investigate some edge cases: simultaneous charging/discharging (looks like E+ just charges and ignores discharge), how fractional values are handled in the schedule, how values > 1 are handled (and how max charging/discharging rate plays in)
- Jeff to look more into outputs from homes with batteries, both with and without PV, in HPXML context

**Comment by jmaguire1** [comment]
Some progress on the outputs! The biggest change was that we were using the wrong bus type. I went from this:

![image](https://user-images.githubusercontent.com/8376057/184262191-8df4c8fa-45b4-46ee-a4e8-b5a64815f666.png)

to this:

![image](https://user-images.githubusercontent.com/8376057/184262209-3df7e128-fcd9-4219-af1f-7bab18680dda.png)

This puts the inverter before the battery, ensuring we have consistent outputs from the PV between base-pv-battery and base-pv-battery-scheduled. I just committed a change that seemed to have worked on my end, feel free to test it out yourself.

I'd like to do a little bit more checking of the outputs just to make sure they're all as expected and then think about any additional outputs we might want to add. REopt has a calculation for "Average Resiliency Hours" that we might want to consider adopting. The Average Resiliency Hours are calculated as a post processing step where you use the battery SoC and the load profile over the next several hours to figure out how long the battery would have been able to support the electrical loads in the house. That calculation is done for every timestep and then averaged to get to Average Resiliency Hours. One simplification it makes is that it's assuming an outage is equally likely to happen every hour, but it's relatively simple to code and it's an already adopted metric. I actually have the code for this in python from REopt in case that's clearer than my explanation:

`

    def simulate_outage(init_time_step, batt_kwh, batt_kw, batt_roundtrip_efficiency, batt_soc_kwh, crit_load, n_timesteps):
        for i in range(n_timesteps):
            t = (init_time_step + i) % n_timesteps  # for wrapping around end of year
            load_kw = crit_load[t]
    
            if load_kw < 0:  # load is met
                if batt_soc_kwh < batt_kwh:  # charge battery if there's room in the battery
                    batt_soc_kwh += min( 
                        batt_kwh - batt_soc_kwh,     # room available
                        batt_kw  * batt_roundtrip_efficiency,  # inverter capacity
                        -load_kw  * batt_roundtrip_efficiency,  # excess energy
                    )
            else:  # check if we can meet load with generator then storage
                if min(batt_kw, batt_soc_kwh) >= load_kw:  # battery can carry balance
                    # prevent battery charge from going negative
                    batt_soc_kwh = max(0, batt_soc_kwh - load_kw)
                    load_kw = 0
    
            if round(load_kw, 5) > 0:  # failed to meet load in this time step
                return float(i) 
    
        return n_timesteps   # met the critical load for all time steps`

I'm about to leave town for a few days, leaving this as food for thought. Let's catch up later next week when I'm back.

**Comment by joseph-robertson** [comment]
Switching to `DirectCurrentWithInverterACStorage` seemed to do the trick. We are now able to meter inverter energy losses on the PV end use, and (optional if battery scheduled) converter energy losses on the Battery end use.

In terms of "Average Resiliency Hours", where would something like this be reported? Integrated into our standard set of reported outputs (annual, timeseries) reports? Or handled separately with its own measure? If the latter, where should the reporting measure be stored?

@jmaguire1 @shorowit

**Comment by shorowit** [comment]
I suggest we get the critical capabilities merged first and then can circle back later if there are some nice-to-haves.

**Comment by jmaguire1** [comment]
I'm on board with what @shorowit suggested, that we wrap up getting the outputs we have correct then look at Average Resiliency Hours and any other metrics we might want.

Where does that leave us on TODOs for this? I think with scheduled battery charging/discharging working that gives us a dispatch strategy for no PV AND additional dispatch for PV cases, and now that we're using the right bus outputs seem to be correct. I could see maybe adding some schedule error checking as a nice to have (charging and discharging during the same hour being the key thing that comes to mind), but are there other things I'm not thinking of? @joseph-robertson

**Comment by joseph-robertson** [comment]
@jmaguire1 Following up on Average Resiliency Hours...

This is an annual metric (i.e., might show up in `results_annual.csv`), but requires that you request information about the battery (at timestep) post simulation?

Can you provide more detail on the arguments to the `simulate_outage` method above? I think I'd need to map these to output variable / meter requests.
