### ISSUE TITLE
BuildResidentialHPXML measure: Allow walkout basements

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#918]
Allow conditioned walk out basements in BuildResHPXML. Unlike regular conditioned basements, these would be included as part of number of stories above-grade. Not sure what measure arguments would be needed to support this.

**Comment by joseph-robertson** [comment]
`base-foundation-walkout-basement.xml`

**Comment by shorowit** [comment]
This is probably too complex and niche of a situation to support.
