### ISSUE TITLE
Add neighbors for shading

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#92]
Add an HPXML test file (via the Rakefile) with neighbors specified. HPXML doesn't really have a good place for it, so I suggest using an extension in the `Site` element like so: 

```
        <Site>
          <extension>
            <Neighbors>
              <NeighborBuilding>
                <Azimuth>45</Azimuth> # neighbor is to the northeast
                <Distance>10</Distance> # ft away
              </NeighborBuilding>
              <NeighborBuilding>
                <Azimuth>225</Azimuth> # neighbor is to the southwest
                <Distance>15</Distance> # ft away
            </NeighborBuilding>
          </Neighbors>
        </Site>
```

Note that we don't know the front of the home, so neighbors are defined in HPXML based on azimuth instead of FBLR. 

Because we have exploded surfaces rather than full 3d geometry in our model, instead of copying all the surfaces from the main building, let's simply add 1 shading surface for each azimuth at the specified distance from that azimuth's surfaces. Each shading surface will be the height of the building, and the width can be set to [max_azimuth_length](https://github.com/NREL/OpenStudio-HPXML/blob/master/measure.rb#L522).

So a building that looks like this without neighbors:
![image](https://user-images.githubusercontent.com/5861765/57412728-f890d400-71ae-11e9-9f35-6a95a6f82729.png)

might look like this with neighbors:
![image](https://user-images.githubusercontent.com/5861765/57412767-28d87280-71af-11e9-995b-a21c5412c9e1.png)

We should also add tests that verify the number of shading surfaces (and their azimuth, if possible).

Needed for https://github.com/NREL/OpenStudio-HEScore/issues/52

**Comment by joseph-robertson** [comment]
What if there exists a neighbor whose azimuth doesn't match any other surface or subsurface azimuth? What should the area of the neighbor shading surface be in this case?

@shorowit

**Comment by shorowit** [comment]
The shading surface in any direction has identical area, since it's just dependent on the building height and max_azimuth_length. Or am I missing a nuance here?

**Comment by joseph-robertson** [comment]
In your second screenshot, which set of surfaces gets the neighbor shading surface, e.g., at 10 ft and at 15 ft?
