### ISSUE TITLE
Utility bill calculation measure

### ISSUE THREAD

**Issue by shorowit** [NREL/OpenStudio-HPXML#920]
SAM SDK?
- bundled in energyplus

Alternatives?
- dGen (Pieter Gagnon)
- python with openstudio (pycall)
- python OpenStudio measure that calls SAM?
- EMS?
- https://github.com/NREL/EnergyPlus/issues/9154

**Comment by joseph-robertson** [comment]
FYI The `UtilityBillCalculations` reporting measure last appeared in ResStock v2.0.0: https://github.com/NREL/resstock/tree/v2.0.0/measures/UtilityBillCalculations

**Comment by joseph-robertson** [comment]
Checklist:
- [ ] dGen for selection of tariffs
- [ ] Need to look into ffi / fiddle
- [ ] Issues with PV (sellback rates, etc.) and use of `utilityrate3`, `utilityrate5`, etc.
- [ ] Issues with leap years

**Comment by joseph-robertson** [comment]
On python measure release, Kyle says: "im not sure. i guess I need to talk to Tim about that. I'm wrestling with some technical issues with Ruby at the moment that I don't have a solution for. I think I'll be able to resolve but not sure"

**Comment by joseph-robertson** [comment]
On ffi, Julien has created a test PR for adding it to the OS CLI: https://github.com/NREL/openstudio-gems/pull/52

**Comment by joseph-robertson** [comment]
From https://openei.org/services/doc/rest/util_rates/?version=3:

OpenEI retired the version 1 API on January 2nd, 2014. Version 2 was released on May 4th, 2013, and version 3 was released on June 16th, 2014, at which point version 2 database updates ceased, with all updates now appearing only in version 3 or greater. Please contact the OpenEI Webmaster if you have any questions or concerns.

**Comment by joseph-robertson** [comment]
Plan:

Step 1
- [ ] Create a new `ReportUtilityBills` measure
- [ ] Start with existing `UtilityBillCalculations` measure, at least in terms of arguments
- [ ] Start with simple electric bills, fossil fuel bills
- [ ] Support only latest version of URDB tariffs?
- [ ] Support only full annual utility bill calculations
- [ ] Need monthly output
  - [ ] Start with E+ consumption output (DSE would have different outputs)
  - [ ] TODO: see below
- [ ] Add unit tests
- [ ] Enable "auto" arguments for state averages (Electricity.csv, Gas.csv, etc.)

Steps 2 and 3
- [ ] Detailed bills (URDB considerations, etc.)
- [ ] Real-time pricing (is this "schema" created by BEopt?)
- [ ] Get consumption from `ReportSimulationOutput` (perhaps call reporting measure from utility bill measure)

**Comment by joseph-robertson** [comment]
Take advantage of dGen's method (list?) for choosing best URDB tariff.

Do we want to ship locally a cache of tariffs? Or make it BYOT ("bring your own tariff")?

**Comment by joseph-robertson** [comment]
BEopt utility bill calculation resources:
* https://github.com/NREL/BEopt2/blob/master/Modeling/output.py#L1032-L1426
* https://github.com/NREL/BEopt2/blob/master/Modeling/utility_rate.py

**Comment by ejhw** [comment]
FYI, I was just informed that the URDB now indicates which rate is the "default" rate, e.g., https://apps.openei.org/USURDB/?utilRateFinder=Xcel+Energy+of+Colorado&service_type=&is_default=1&search=

**Comment by joseph-robertson** [comment]
Meeting notes for detailed bill calculations:
* Don't allow autoselection of tariff(s)
* Real-time pricing
  * Should be pretty simple
  * Point to csv file
* OpenEI tariff
  * Demand charges (probably leave these out)
    * BEopt didn't support demand charges
    * We could see how common they are
  * Package collection of tariffs (like BEopt)
    * Download them in bulk?

**Comment by joseph-robertson** [comment]
Another idea is to support reading utility rate information from the HPXML file itself, vs entering them in the `ReportUtilityBills` reporting measure. Consider supporting multiple utility rate scenarios (similar to emissions).
