### ISSUE TITLE
Metal frame double-pane low-e window cannot lookup UFactor and SHGC

### ISSUE THREAD

**Issue by yzhou601** [NREL/OpenStudio-HPXML#941]
@shorowit If a window is specified as `GlassLayers = double-pane, GlassType=low-e, FrameType=Aluminum` with other inputs being defaulted, there'll be an error: `Error: Could not lookup UFactor and SHGC for window 'Window1'.`

In the defaulting, thermal break will be defaulted to be `true` (lack documentation to describe this behavior that [it will be `true` for double-pane metal frame windows, while `false` for single-pane metal frame windows](https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/hpxml_defaults.rb#L637-L643)), and the gas will be defaulted to be `air` for double-pane windows. 

In this way, there's no valid mapping in the lookup table for this kind of windows because the gas cannot be air for double-pane low-e metal windows: https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id186 .

Example window specification that will capture the error:

          <Window>
            <SystemIdentifier id='Window1'/>
            <Area>102.8571429</Area>
            <Azimuth>0</Azimuth>
            <Orientation>north</Orientation>
            <FrameType>
              <Aluminum/>
            </FrameType>
            <GlassLayers>double-pane</GlassLayers>
            <GlassType>low-e</GlassType>
            <AttachedToWall idref='Wall1'/>
          </Window>

Questions:
1. Is the window specification itself not allowed? If so, we can simply ignore this error because documentation indicates a warning for improper mapping: OpenStudio-HPXML will return an error if the combination of window properties is not in the above table.
2. Or is the defaulting supposed to be changed so that the air can be defaulted to 'gas' so that the specification can be allowed?
3. Should the documentation be updated to reflect the thermal break defaulting difference for single-pane and double-pane windows?

**Comment by shorowit** [comment]
@yzhou601 We're intending to support the same options that HEScore supports (though obviously we could expand support if we wanted to). Can you compare [LBL's documentation](http://hes-documentation.lbl.gov/calculation-methodology/calculation-of-energy-consumption/heating-and-cooling-calculation/building-envelope/window-skylight-construction-types), [hescore-hpxml's documentation](https://hescore-hpxml.readthedocs.io/en/latest/translation/zone_window.html), and the image below to what we [support in OS-HPXML](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id186)? I don't know offhand if it's a bug, limitation, or otherwise.

![image](https://user-images.githubusercontent.com/5861765/146975681-943da4fc-4fbe-4df6-8969-e39bfb634186.png)

**Comment by yzhou601** [comment]
Is our os-hpxml mapping (or [OS-HEScore mapping](https://github.com/NREL/OpenStudio-HEScore/blob/master/rulesets/HEScoreRuleset/resources/HESruleset.rb#L1235-L1256)) supposed to be the same as LBL's mapping? I couldn't see consistent mapped U/SHGC values between these two. 

I think the issue is that there's a difference in `solar-control low-e` and `insulating low-e` (is this the same as passive low-e?), which is not clear how to differentiate when specifying HPXML for a more general purpose. It is likely that an 'aluminum double pane low-e' window is a double-pane, **solar-control low-e** (with thermal break: dseab; without thermal break: dseaa), or it can be a double-pane **insulating low-e** with thermal break and **argon gas fill**(dpeaab), which are able to be mapped here. But the current approach is not supporting it because it is assuming `low-e` GlassType to be **insulating low-e**, and defaulting double-pane metal frame windows to be **air-filled** with thermal break. This aligns with hpxml-hescore translator which treats `reflective` as solar-control low-e, and `low-e` as insulating low-e (See warning in the section [here](https://hescore-hpxml.readthedocs.io/en/latest/translation/zone_window.html#double-pane-1)) If we assume the same inputs that solar-control low-e should be specified as 'reflective' and insulating low-e to be 'low-e', then maybe we can : 

1. explicitly specify that low-e means insulating low-e in the documentation, consistent with hpxml-hescore doc; If a solar-controlled low-e is expected, then use reflective as GlassType
2. For the unspecified gas filled, add a check in defaulting that if it's a metal framed insulating low-e, fill it with argon (because this is the only option that can be mapped to); Or, retain the current approach that user has to explicitly specify valid combinations otherwise it is likely to fail. I think both are reasonable, it's fair that if the window is argon filled, user should put it into the HPXML.

Another option is to add enumerations to HPXML `GlassType` element to explicitly differentiate these two types of low-e coating. This makes it more clear to users what glass types we are mapping to.

**Comment by shorowit** [comment]
Turns out there is a [second HEScore window table](https://docs.google.com/spreadsheets/d/1joG39BeiRj1mV0Lge91P_dkL-0-94lSEY5tJzGvpc2A/edit#gid=909262753). Not sure how it's different than the other one, but our window options reflect this one.

**Comment by shorowit** [comment]
According to LBL, this second table ([here](https://docs.google.com/spreadsheets/d/1joG39BeiRj1mV0Lge91P_dkL-0-94lSEY5tJzGvpc2A/edit#gid=909262753), and also found [here](http://hes-documentation.lbl.gov/calculation-methodology/calculation-of-energy-consumption/heating-and-cooling-calculation/doe2-inputs-assumptions-and-calculations/doe2-inputs)) is indeed the correct one. They didn't immediately know where the other table came from.

**Comment by yzhou601** [comment]
> According to LBL, this second table ([here](https://docs.google.com/spreadsheets/d/1joG39BeiRj1mV0Lge91P_dkL-0-94lSEY5tJzGvpc2A/edit#gid=909262753), and also found [here](http://hes-documentation.lbl.gov/calculation-methodology/calculation-of-energy-consumption/heating-and-cooling-calculation/doe2-inputs-assumptions-and-calculations/doe2-inputs)) is indeed the correct one. They didn't immediately know where the other table came from.

Sounds like they're having two inconsistent docs, and what we're using is correct?

**Comment by shorowit** [comment]
https://github.com/hpxmlwg/hpxml/issues/329
